/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the BorrowerCategory service. Represents a row in the &quot;eis_BorrowerCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.BorrowerCategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.BorrowerCategoryImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see BorrowerCategory
 * @see com.idetronic.eis.model.impl.BorrowerCategoryImpl
 * @see com.idetronic.eis.model.impl.BorrowerCategoryModelImpl
 * @generated
 */
public interface BorrowerCategoryModel extends BaseModel<BorrowerCategory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a borrower category model instance should use the {@link BorrowerCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this borrower category.
	 *
	 * @return the primary key of this borrower category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this borrower category.
	 *
	 * @param primaryKey the primary key of this borrower category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the borrower category ID of this borrower category.
	 *
	 * @return the borrower category ID of this borrower category
	 */
	public long getBorrowerCategoryId();

	/**
	 * Sets the borrower category ID of this borrower category.
	 *
	 * @param borrowerCategoryId the borrower category ID of this borrower category
	 */
	public void setBorrowerCategoryId(long borrowerCategoryId);

	/**
	 * Returns the borrower category name of this borrower category.
	 *
	 * @return the borrower category name of this borrower category
	 */
	@AutoEscape
	public String getBorrowerCategoryName();

	/**
	 * Sets the borrower category name of this borrower category.
	 *
	 * @param borrowerCategoryName the borrower category name of this borrower category
	 */
	public void setBorrowerCategoryName(String borrowerCategoryName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.idetronic.eis.model.BorrowerCategory borrowerCategory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.BorrowerCategory> toCacheModel();

	@Override
	public com.idetronic.eis.model.BorrowerCategory toEscapedModel();

	@Override
	public com.idetronic.eis.model.BorrowerCategory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}