/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Config service. Represents a row in the &quot;eis_Config&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.ConfigModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.ConfigImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see Config
 * @see com.idetronic.eis.model.impl.ConfigImpl
 * @see com.idetronic.eis.model.impl.ConfigModelImpl
 * @generated
 */
public interface ConfigModel extends BaseModel<Config> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a config model instance should use the {@link Config} interface instead.
	 */

	/**
	 * Returns the primary key of this config.
	 *
	 * @return the primary key of this config
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this config.
	 *
	 * @param primaryKey the primary key of this config
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this config.
	 *
	 * @return the ID of this config
	 */
	public long getId();

	/**
	 * Sets the ID of this config.
	 *
	 * @param id the ID of this config
	 */
	public void setId(long id);

	/**
	 * Returns the key of this config.
	 *
	 * @return the key of this config
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this config.
	 *
	 * @param key the key of this config
	 */
	public void setKey(String key);

	/**
	 * Returns the value of this config.
	 *
	 * @return the value of this config
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this config.
	 *
	 * @param value the value of this config
	 */
	public void setValue(String value);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.eis.model.Config config);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.Config> toCacheModel();

	@Override
	public com.idetronic.eis.model.Config toEscapedModel();

	@Override
	public com.idetronic.eis.model.Config toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}