/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FactConsultation service. Represents a row in the &quot;eis_FactConsultation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.FactConsultationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.FactConsultationImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see FactConsultation
 * @see com.idetronic.eis.model.impl.FactConsultationImpl
 * @see com.idetronic.eis.model.impl.FactConsultationModelImpl
 * @generated
 */
public interface FactConsultationModel extends BaseModel<FactConsultation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fact consultation model instance should use the {@link FactConsultation} interface instead.
	 */

	/**
	 * Returns the primary key of this fact consultation.
	 *
	 * @return the primary key of this fact consultation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fact consultation.
	 *
	 * @param primaryKey the primary key of this fact consultation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the fact consultation ID of this fact consultation.
	 *
	 * @return the fact consultation ID of this fact consultation
	 */
	public long getFactConsultationId();

	/**
	 * Sets the fact consultation ID of this fact consultation.
	 *
	 * @param factConsultationId the fact consultation ID of this fact consultation
	 */
	public void setFactConsultationId(long factConsultationId);

	/**
	 * Returns the library ID of this fact consultation.
	 *
	 * @return the library ID of this fact consultation
	 */
	public long getLibraryId();

	/**
	 * Sets the library ID of this fact consultation.
	 *
	 * @param libraryId the library ID of this fact consultation
	 */
	public void setLibraryId(long libraryId);

	/**
	 * Returns the period of this fact consultation.
	 *
	 * @return the period of this fact consultation
	 */
	@AutoEscape
	public String getPeriod();

	/**
	 * Sets the period of this fact consultation.
	 *
	 * @param period the period of this fact consultation
	 */
	public void setPeriod(String period);

	/**
	 * Returns the consultation group ID of this fact consultation.
	 *
	 * @return the consultation group ID of this fact consultation
	 */
	public long getConsultationGroupId();

	/**
	 * Sets the consultation group ID of this fact consultation.
	 *
	 * @param consultationGroupId the consultation group ID of this fact consultation
	 */
	public void setConsultationGroupId(long consultationGroupId);

	/**
	 * Returns the consultation category ID of this fact consultation.
	 *
	 * @return the consultation category ID of this fact consultation
	 */
	public long getConsultationCategoryId();

	/**
	 * Sets the consultation category ID of this fact consultation.
	 *
	 * @param consultationCategoryId the consultation category ID of this fact consultation
	 */
	public void setConsultationCategoryId(long consultationCategoryId);

	/**
	 * Returns the value of this fact consultation.
	 *
	 * @return the value of this fact consultation
	 */
	public long getValue();

	/**
	 * Sets the value of this fact consultation.
	 *
	 * @param value the value of this fact consultation
	 */
	public void setValue(long value);

	/**
	 * Returns the total session of this fact consultation.
	 *
	 * @return the total session of this fact consultation
	 */
	public long getTotalSession();

	/**
	 * Sets the total session of this fact consultation.
	 *
	 * @param totalSession the total session of this fact consultation
	 */
	public void setTotalSession(long totalSession);

	/**
	 * Returns the company ID of this fact consultation.
	 *
	 * @return the company ID of this fact consultation
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this fact consultation.
	 *
	 * @param companyId the company ID of this fact consultation
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this fact consultation.
	 *
	 * @return the group ID of this fact consultation
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this fact consultation.
	 *
	 * @param groupId the group ID of this fact consultation
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this fact consultation.
	 *
	 * @return the user ID of this fact consultation
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this fact consultation.
	 *
	 * @param userId the user ID of this fact consultation
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this fact consultation.
	 *
	 * @return the user uuid of this fact consultation
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this fact consultation.
	 *
	 * @param userUuid the user uuid of this fact consultation
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this fact consultation.
	 *
	 * @return the user name of this fact consultation
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this fact consultation.
	 *
	 * @param userName the user name of this fact consultation
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this fact consultation.
	 *
	 * @return the create date of this fact consultation
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this fact consultation.
	 *
	 * @param createDate the create date of this fact consultation
	 */
	public void setCreateDate(Date createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.idetronic.eis.model.FactConsultation factConsultation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.FactConsultation> toCacheModel();

	@Override
	public com.idetronic.eis.model.FactConsultation toEscapedModel();

	@Override
	public com.idetronic.eis.model.FactConsultation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}