/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FactCustomerComplaint service. Represents a row in the &quot;eis_FactCustomerComplaint&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.FactCustomerComplaintModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.FactCustomerComplaintImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see FactCustomerComplaint
 * @see com.idetronic.eis.model.impl.FactCustomerComplaintImpl
 * @see com.idetronic.eis.model.impl.FactCustomerComplaintModelImpl
 * @generated
 */
public interface FactCustomerComplaintModel extends BaseModel<FactCustomerComplaint> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fact customer complaint model instance should use the {@link FactCustomerComplaint} interface instead.
	 */

	/**
	 * Returns the primary key of this fact customer complaint.
	 *
	 * @return the primary key of this fact customer complaint
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fact customer complaint.
	 *
	 * @param primaryKey the primary key of this fact customer complaint
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the fact ID of this fact customer complaint.
	 *
	 * @return the fact ID of this fact customer complaint
	 */
	public long getFactId();

	/**
	 * Sets the fact ID of this fact customer complaint.
	 *
	 * @param factId the fact ID of this fact customer complaint
	 */
	public void setFactId(long factId);

	/**
	 * Returns the library ID of this fact customer complaint.
	 *
	 * @return the library ID of this fact customer complaint
	 */
	public long getLibraryId();

	/**
	 * Sets the library ID of this fact customer complaint.
	 *
	 * @param libraryId the library ID of this fact customer complaint
	 */
	public void setLibraryId(long libraryId);

	/**
	 * Returns the period of this fact customer complaint.
	 *
	 * @return the period of this fact customer complaint
	 */
	@AutoEscape
	public String getPeriod();

	/**
	 * Sets the period of this fact customer complaint.
	 *
	 * @param period the period of this fact customer complaint
	 */
	public void setPeriod(String period);

	/**
	 * Returns the complaint total of this fact customer complaint.
	 *
	 * @return the complaint total of this fact customer complaint
	 */
	public long getComplaintTotal();

	/**
	 * Sets the complaint total of this fact customer complaint.
	 *
	 * @param complaintTotal the complaint total of this fact customer complaint
	 */
	public void setComplaintTotal(long complaintTotal);

	/**
	 * Returns the unsettled total of this fact customer complaint.
	 *
	 * @return the unsettled total of this fact customer complaint
	 */
	public long getUnsettledTotal();

	/**
	 * Sets the unsettled total of this fact customer complaint.
	 *
	 * @param unsettledTotal the unsettled total of this fact customer complaint
	 */
	public void setUnsettledTotal(long unsettledTotal);

	/**
	 * Returns the company ID of this fact customer complaint.
	 *
	 * @return the company ID of this fact customer complaint
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this fact customer complaint.
	 *
	 * @param companyId the company ID of this fact customer complaint
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this fact customer complaint.
	 *
	 * @return the group ID of this fact customer complaint
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this fact customer complaint.
	 *
	 * @param groupId the group ID of this fact customer complaint
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this fact customer complaint.
	 *
	 * @return the user ID of this fact customer complaint
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this fact customer complaint.
	 *
	 * @param userId the user ID of this fact customer complaint
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this fact customer complaint.
	 *
	 * @return the user uuid of this fact customer complaint
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this fact customer complaint.
	 *
	 * @param userUuid the user uuid of this fact customer complaint
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this fact customer complaint.
	 *
	 * @return the user name of this fact customer complaint
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this fact customer complaint.
	 *
	 * @param userName the user name of this fact customer complaint
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this fact customer complaint.
	 *
	 * @return the create date of this fact customer complaint
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this fact customer complaint.
	 *
	 * @param createDate the create date of this fact customer complaint
	 */
	public void setCreateDate(Date createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.idetronic.eis.model.FactCustomerComplaint factCustomerComplaint);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.FactCustomerComplaint> toCacheModel();

	@Override
	public com.idetronic.eis.model.FactCustomerComplaint toEscapedModel();

	@Override
	public com.idetronic.eis.model.FactCustomerComplaint toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}