/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FactMembership service. Represents a row in the &quot;eis_FactMembership&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.FactMembershipModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.FactMembershipImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see FactMembership
 * @see com.idetronic.eis.model.impl.FactMembershipImpl
 * @see com.idetronic.eis.model.impl.FactMembershipModelImpl
 * @generated
 */
public interface FactMembershipModel extends BaseModel<FactMembership> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fact membership model instance should use the {@link FactMembership} interface instead.
	 */

	/**
	 * Returns the primary key of this fact membership.
	 *
	 * @return the primary key of this fact membership
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fact membership.
	 *
	 * @param primaryKey the primary key of this fact membership
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the fact membership ID of this fact membership.
	 *
	 * @return the fact membership ID of this fact membership
	 */
	public long getFactMembershipId();

	/**
	 * Sets the fact membership ID of this fact membership.
	 *
	 * @param factMembershipId the fact membership ID of this fact membership
	 */
	public void setFactMembershipId(long factMembershipId);

	/**
	 * Returns the library ID of this fact membership.
	 *
	 * @return the library ID of this fact membership
	 */
	public long getLibraryId();

	/**
	 * Sets the library ID of this fact membership.
	 *
	 * @param libraryId the library ID of this fact membership
	 */
	public void setLibraryId(long libraryId);

	/**
	 * Returns the period of this fact membership.
	 *
	 * @return the period of this fact membership
	 */
	@AutoEscape
	public String getPeriod();

	/**
	 * Sets the period of this fact membership.
	 *
	 * @param period the period of this fact membership
	 */
	public void setPeriod(String period);

	/**
	 * Returns the state ID of this fact membership.
	 *
	 * @return the state ID of this fact membership
	 */
	public long getStateId();

	/**
	 * Sets the state ID of this fact membership.
	 *
	 * @param stateId the state ID of this fact membership
	 */
	public void setStateId(long stateId);

	/**
	 * Returns the library type ID of this fact membership.
	 *
	 * @return the library type ID of this fact membership
	 */
	public long getLibraryTypeId();

	/**
	 * Sets the library type ID of this fact membership.
	 *
	 * @param libraryTypeId the library type ID of this fact membership
	 */
	public void setLibraryTypeId(long libraryTypeId);

	/**
	 * Returns the membership category ID of this fact membership.
	 *
	 * @return the membership category ID of this fact membership
	 */
	public long getMembershipCategoryId();

	/**
	 * Sets the membership category ID of this fact membership.
	 *
	 * @param membershipCategoryId the membership category ID of this fact membership
	 */
	public void setMembershipCategoryId(long membershipCategoryId);

	/**
	 * Returns the active count of this fact membership.
	 *
	 * @return the active count of this fact membership
	 */
	public int getActiveCount();

	/**
	 * Sets the active count of this fact membership.
	 *
	 * @param activeCount the active count of this fact membership
	 */
	public void setActiveCount(int activeCount);

	/**
	 * Returns the company ID of this fact membership.
	 *
	 * @return the company ID of this fact membership
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this fact membership.
	 *
	 * @param companyId the company ID of this fact membership
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this fact membership.
	 *
	 * @return the group ID of this fact membership
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this fact membership.
	 *
	 * @param groupId the group ID of this fact membership
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this fact membership.
	 *
	 * @return the user ID of this fact membership
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this fact membership.
	 *
	 * @param userId the user ID of this fact membership
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this fact membership.
	 *
	 * @return the user uuid of this fact membership
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this fact membership.
	 *
	 * @param userUuid the user uuid of this fact membership
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this fact membership.
	 *
	 * @return the user name of this fact membership
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this fact membership.
	 *
	 * @param userName the user name of this fact membership
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this fact membership.
	 *
	 * @return the create date of this fact membership
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this fact membership.
	 *
	 * @param createDate the create date of this fact membership
	 */
	public void setCreateDate(Date createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.eis.model.FactMembership factMembership);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.FactMembership> toCacheModel();

	@Override
	public com.idetronic.eis.model.FactMembership toEscapedModel();

	@Override
	public com.idetronic.eis.model.FactMembership toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}