/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FactVisitor service. Represents a row in the &quot;eis_FactVisitor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.FactVisitorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.FactVisitorImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see FactVisitor
 * @see com.idetronic.eis.model.impl.FactVisitorImpl
 * @see com.idetronic.eis.model.impl.FactVisitorModelImpl
 * @generated
 */
public interface FactVisitorModel extends BaseModel<FactVisitor> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fact visitor model instance should use the {@link FactVisitor} interface instead.
	 */

	/**
	 * Returns the primary key of this fact visitor.
	 *
	 * @return the primary key of this fact visitor
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fact visitor.
	 *
	 * @param primaryKey the primary key of this fact visitor
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the fact visitor ID of this fact visitor.
	 *
	 * @return the fact visitor ID of this fact visitor
	 */
	public long getFactVisitorId();

	/**
	 * Sets the fact visitor ID of this fact visitor.
	 *
	 * @param factVisitorId the fact visitor ID of this fact visitor
	 */
	public void setFactVisitorId(long factVisitorId);

	/**
	 * Returns the library ID of this fact visitor.
	 *
	 * @return the library ID of this fact visitor
	 */
	public long getLibraryId();

	/**
	 * Sets the library ID of this fact visitor.
	 *
	 * @param libraryId the library ID of this fact visitor
	 */
	public void setLibraryId(long libraryId);

	/**
	 * Returns the period of this fact visitor.
	 *
	 * @return the period of this fact visitor
	 */
	@AutoEscape
	public String getPeriod();

	/**
	 * Sets the period of this fact visitor.
	 *
	 * @param period the period of this fact visitor
	 */
	public void setPeriod(String period);

	/**
	 * Returns the visitor category ID of this fact visitor.
	 *
	 * @return the visitor category ID of this fact visitor
	 */
	public long getVisitorCategoryId();

	/**
	 * Sets the visitor category ID of this fact visitor.
	 *
	 * @param visitorCategoryId the visitor category ID of this fact visitor
	 */
	public void setVisitorCategoryId(long visitorCategoryId);

	/**
	 * Returns the state ID of this fact visitor.
	 *
	 * @return the state ID of this fact visitor
	 */
	public long getStateId();

	/**
	 * Sets the state ID of this fact visitor.
	 *
	 * @param stateId the state ID of this fact visitor
	 */
	public void setStateId(long stateId);

	/**
	 * Returns the library type ID of this fact visitor.
	 *
	 * @return the library type ID of this fact visitor
	 */
	public long getLibraryTypeId();

	/**
	 * Sets the library type ID of this fact visitor.
	 *
	 * @param libraryTypeId the library type ID of this fact visitor
	 */
	public void setLibraryTypeId(long libraryTypeId);

	/**
	 * Returns the value of this fact visitor.
	 *
	 * @return the value of this fact visitor
	 */
	public int getValue();

	/**
	 * Sets the value of this fact visitor.
	 *
	 * @param value the value of this fact visitor
	 */
	public void setValue(int value);

	/**
	 * Returns the created by user ID of this fact visitor.
	 *
	 * @return the created by user ID of this fact visitor
	 */
	public long getCreatedByUserId();

	/**
	 * Sets the created by user ID of this fact visitor.
	 *
	 * @param createdByUserId the created by user ID of this fact visitor
	 */
	public void setCreatedByUserId(long createdByUserId);

	/**
	 * Returns the created by user uuid of this fact visitor.
	 *
	 * @return the created by user uuid of this fact visitor
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreatedByUserUuid() throws SystemException;

	/**
	 * Sets the created by user uuid of this fact visitor.
	 *
	 * @param createdByUserUuid the created by user uuid of this fact visitor
	 */
	public void setCreatedByUserUuid(String createdByUserUuid);

	/**
	 * Returns the created by user name of this fact visitor.
	 *
	 * @return the created by user name of this fact visitor
	 */
	@AutoEscape
	public String getCreatedByUserName();

	/**
	 * Sets the created by user name of this fact visitor.
	 *
	 * @param createdByUserName the created by user name of this fact visitor
	 */
	public void setCreatedByUserName(String createdByUserName);

	/**
	 * Returns the created date of this fact visitor.
	 *
	 * @return the created date of this fact visitor
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this fact visitor.
	 *
	 * @param createdDate the created date of this fact visitor
	 */
	public void setCreatedDate(Date createdDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.eis.model.FactVisitor factVisitor);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.FactVisitor> toCacheModel();

	@Override
	public com.idetronic.eis.model.FactVisitor toEscapedModel();

	@Override
	public com.idetronic.eis.model.FactVisitor toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}