/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FactExpense service. Represents a row in the &quot;eis_FactExpense&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.FactExpenseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.FactExpenseImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see FactExpense
 * @see com.idetronic.eis.model.impl.FactExpenseImpl
 * @see com.idetronic.eis.model.impl.FactExpenseModelImpl
 * @generated
 */
public interface FactExpenseModel extends BaseModel<FactExpense> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fact expense model instance should use the {@link FactExpense} interface instead.
	 */

	/**
	 * Returns the primary key of this fact expense.
	 *
	 * @return the primary key of this fact expense
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fact expense.
	 *
	 * @param primaryKey the primary key of this fact expense
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the fact expense ID of this fact expense.
	 *
	 * @return the fact expense ID of this fact expense
	 */
	public long getFactExpenseId();

	/**
	 * Sets the fact expense ID of this fact expense.
	 *
	 * @param factExpenseId the fact expense ID of this fact expense
	 */
	public void setFactExpenseId(long factExpenseId);

	/**
	 * Returns the library ID of this fact expense.
	 *
	 * @return the library ID of this fact expense
	 */
	public long getLibraryId();

	/**
	 * Sets the library ID of this fact expense.
	 *
	 * @param libraryId the library ID of this fact expense
	 */
	public void setLibraryId(long libraryId);

	/**
	 * Returns the period of this fact expense.
	 *
	 * @return the period of this fact expense
	 */
	@AutoEscape
	public String getPeriod();

	/**
	 * Sets the period of this fact expense.
	 *
	 * @param period the period of this fact expense
	 */
	public void setPeriod(String period);

	/**
	 * Returns the entry type of this fact expense.
	 *
	 * @return the entry type of this fact expense
	 */
	public int getEntryType();

	/**
	 * Sets the entry type of this fact expense.
	 *
	 * @param entryType the entry type of this fact expense
	 */
	public void setEntryType(int entryType);

	/**
	 * Returns the master file ID of this fact expense.
	 *
	 * @return the master file ID of this fact expense
	 */
	public long getMasterFileId();

	/**
	 * Sets the master file ID of this fact expense.
	 *
	 * @param masterFileId the master file ID of this fact expense
	 */
	public void setMasterFileId(long masterFileId);

	/**
	 * Returns the amount of this fact expense.
	 *
	 * @return the amount of this fact expense
	 */
	public double getAmount();

	/**
	 * Sets the amount of this fact expense.
	 *
	 * @param amount the amount of this fact expense
	 */
	public void setAmount(double amount);

	/**
	 * Returns the company ID of this fact expense.
	 *
	 * @return the company ID of this fact expense
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this fact expense.
	 *
	 * @param companyId the company ID of this fact expense
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this fact expense.
	 *
	 * @return the group ID of this fact expense
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this fact expense.
	 *
	 * @param groupId the group ID of this fact expense
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this fact expense.
	 *
	 * @return the user ID of this fact expense
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this fact expense.
	 *
	 * @param userId the user ID of this fact expense
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this fact expense.
	 *
	 * @return the user uuid of this fact expense
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this fact expense.
	 *
	 * @param userUuid the user uuid of this fact expense
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this fact expense.
	 *
	 * @return the user name of this fact expense
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this fact expense.
	 *
	 * @param userName the user name of this fact expense
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this fact expense.
	 *
	 * @return the create date of this fact expense
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this fact expense.
	 *
	 * @param createDate the create date of this fact expense
	 */
	public void setCreateDate(Date createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.eis.model.FactExpense factExpense);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.FactExpense> toCacheModel();

	@Override
	public com.idetronic.eis.model.FactExpense toEscapedModel();

	@Override
	public com.idetronic.eis.model.FactExpense toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}