/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FactInternationalPortalUsage service. Represents a row in the &quot;eis_FactInternationalPortalUsage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.FactInternationalPortalUsageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.FactInternationalPortalUsageImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see FactInternationalPortalUsage
 * @see com.idetronic.eis.model.impl.FactInternationalPortalUsageImpl
 * @see com.idetronic.eis.model.impl.FactInternationalPortalUsageModelImpl
 * @generated
 */
public interface FactInternationalPortalUsageModel extends BaseModel<FactInternationalPortalUsage> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fact international portal usage model instance should use the {@link FactInternationalPortalUsage} interface instead.
	 */

	/**
	 * Returns the primary key of this fact international portal usage.
	 *
	 * @return the primary key of this fact international portal usage
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fact international portal usage.
	 *
	 * @param primaryKey the primary key of this fact international portal usage
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the fact ID of this fact international portal usage.
	 *
	 * @return the fact ID of this fact international portal usage
	 */
	public long getFactId();

	/**
	 * Sets the fact ID of this fact international portal usage.
	 *
	 * @param factId the fact ID of this fact international portal usage
	 */
	public void setFactId(long factId);

	/**
	 * Returns the period of this fact international portal usage.
	 *
	 * @return the period of this fact international portal usage
	 */
	@AutoEscape
	public String getPeriod();

	/**
	 * Sets the period of this fact international portal usage.
	 *
	 * @param period the period of this fact international portal usage
	 */
	public void setPeriod(String period);

	/**
	 * Returns the country ID of this fact international portal usage.
	 *
	 * @return the country ID of this fact international portal usage
	 */
	public long getCountryId();

	/**
	 * Sets the country ID of this fact international portal usage.
	 *
	 * @param countryId the country ID of this fact international portal usage
	 */
	public void setCountryId(long countryId);

	/**
	 * Returns the pages total of this fact international portal usage.
	 *
	 * @return the pages total of this fact international portal usage
	 */
	public long getPagesTotal();

	/**
	 * Sets the pages total of this fact international portal usage.
	 *
	 * @param pagesTotal the pages total of this fact international portal usage
	 */
	public void setPagesTotal(long pagesTotal);

	/**
	 * Returns the company ID of this fact international portal usage.
	 *
	 * @return the company ID of this fact international portal usage
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this fact international portal usage.
	 *
	 * @param companyId the company ID of this fact international portal usage
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this fact international portal usage.
	 *
	 * @return the group ID of this fact international portal usage
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this fact international portal usage.
	 *
	 * @param groupId the group ID of this fact international portal usage
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this fact international portal usage.
	 *
	 * @return the user ID of this fact international portal usage
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this fact international portal usage.
	 *
	 * @param userId the user ID of this fact international portal usage
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this fact international portal usage.
	 *
	 * @return the user uuid of this fact international portal usage
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this fact international portal usage.
	 *
	 * @param userUuid the user uuid of this fact international portal usage
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this fact international portal usage.
	 *
	 * @return the user name of this fact international portal usage
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this fact international portal usage.
	 *
	 * @param userName the user name of this fact international portal usage
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this fact international portal usage.
	 *
	 * @return the create date of this fact international portal usage
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this fact international portal usage.
	 *
	 * @param createDate the create date of this fact international portal usage
	 */
	public void setCreateDate(Date createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.idetronic.eis.model.FactInternationalPortalUsage factInternationalPortalUsage);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.FactInternationalPortalUsage> toCacheModel();

	@Override
	public com.idetronic.eis.model.FactInternationalPortalUsage toEscapedModel();

	@Override
	public com.idetronic.eis.model.FactInternationalPortalUsage toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}