/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FactNonPrintedMaterial service. Represents a row in the &quot;eis_FactNonPrintedMaterial&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.FactNonPrintedMaterialModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.FactNonPrintedMaterialImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see FactNonPrintedMaterial
 * @see com.idetronic.eis.model.impl.FactNonPrintedMaterialImpl
 * @see com.idetronic.eis.model.impl.FactNonPrintedMaterialModelImpl
 * @generated
 */
public interface FactNonPrintedMaterialModel extends BaseModel<FactNonPrintedMaterial> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fact non printed material model instance should use the {@link FactNonPrintedMaterial} interface instead.
	 */

	/**
	 * Returns the primary key of this fact non printed material.
	 *
	 * @return the primary key of this fact non printed material
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fact non printed material.
	 *
	 * @param primaryKey the primary key of this fact non printed material
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the fact non printed material ID of this fact non printed material.
	 *
	 * @return the fact non printed material ID of this fact non printed material
	 */
	public long getFactNonPrintedMaterialId();

	/**
	 * Sets the fact non printed material ID of this fact non printed material.
	 *
	 * @param factNonPrintedMaterialId the fact non printed material ID of this fact non printed material
	 */
	public void setFactNonPrintedMaterialId(long factNonPrintedMaterialId);

	/**
	 * Returns the library ID of this fact non printed material.
	 *
	 * @return the library ID of this fact non printed material
	 */
	public long getLibraryId();

	/**
	 * Sets the library ID of this fact non printed material.
	 *
	 * @param libraryId the library ID of this fact non printed material
	 */
	public void setLibraryId(long libraryId);

	/**
	 * Returns the library code of this fact non printed material.
	 *
	 * @return the library code of this fact non printed material
	 */
	@AutoEscape
	public String getLibraryCode();

	/**
	 * Sets the library code of this fact non printed material.
	 *
	 * @param libraryCode the library code of this fact non printed material
	 */
	public void setLibraryCode(String libraryCode);

	/**
	 * Returns the state ID of this fact non printed material.
	 *
	 * @return the state ID of this fact non printed material
	 */
	public long getStateId();

	/**
	 * Sets the state ID of this fact non printed material.
	 *
	 * @param stateId the state ID of this fact non printed material
	 */
	public void setStateId(long stateId);

	/**
	 * Returns the state code of this fact non printed material.
	 *
	 * @return the state code of this fact non printed material
	 */
	@AutoEscape
	public String getStateCode();

	/**
	 * Sets the state code of this fact non printed material.
	 *
	 * @param stateCode the state code of this fact non printed material
	 */
	public void setStateCode(String stateCode);

	/**
	 * Returns the library type ID of this fact non printed material.
	 *
	 * @return the library type ID of this fact non printed material
	 */
	public long getLibraryTypeId();

	/**
	 * Sets the library type ID of this fact non printed material.
	 *
	 * @param libraryTypeId the library type ID of this fact non printed material
	 */
	public void setLibraryTypeId(long libraryTypeId);

	/**
	 * Returns the item type ID of this fact non printed material.
	 *
	 * @return the item type ID of this fact non printed material
	 */
	public long getItemTypeId();

	/**
	 * Sets the item type ID of this fact non printed material.
	 *
	 * @param itemTypeId the item type ID of this fact non printed material
	 */
	public void setItemTypeId(long itemTypeId);

	/**
	 * Returns the period of this fact non printed material.
	 *
	 * @return the period of this fact non printed material
	 */
	@AutoEscape
	public String getPeriod();

	/**
	 * Sets the period of this fact non printed material.
	 *
	 * @param period the period of this fact non printed material
	 */
	public void setPeriod(String period);

	/**
	 * Returns the month val of this fact non printed material.
	 *
	 * @return the month val of this fact non printed material
	 */
	public int getMonthVal();

	/**
	 * Sets the month val of this fact non printed material.
	 *
	 * @param monthVal the month val of this fact non printed material
	 */
	public void setMonthVal(int monthVal);

	/**
	 * Returns the year val of this fact non printed material.
	 *
	 * @return the year val of this fact non printed material
	 */
	public int getYearVal();

	/**
	 * Sets the year val of this fact non printed material.
	 *
	 * @param yearVal the year val of this fact non printed material
	 */
	public void setYearVal(int yearVal);

	/**
	 * Returns the title total of this fact non printed material.
	 *
	 * @return the title total of this fact non printed material
	 */
	public int getTitleTotal();

	/**
	 * Sets the title total of this fact non printed material.
	 *
	 * @param titleTotal the title total of this fact non printed material
	 */
	public void setTitleTotal(int titleTotal);

	/**
	 * Returns the volume total of this fact non printed material.
	 *
	 * @return the volume total of this fact non printed material
	 */
	public int getVolumeTotal();

	/**
	 * Sets the volume total of this fact non printed material.
	 *
	 * @param volumeTotal the volume total of this fact non printed material
	 */
	public void setVolumeTotal(int volumeTotal);

	/**
	 * Returns the date created of this fact non printed material.
	 *
	 * @return the date created of this fact non printed material
	 */
	public Date getDateCreated();

	/**
	 * Sets the date created of this fact non printed material.
	 *
	 * @param dateCreated the date created of this fact non printed material
	 */
	public void setDateCreated(Date dateCreated);

	/**
	 * Returns the created by user name of this fact non printed material.
	 *
	 * @return the created by user name of this fact non printed material
	 */
	@AutoEscape
	public String getCreatedByUserName();

	/**
	 * Sets the created by user name of this fact non printed material.
	 *
	 * @param createdByUserName the created by user name of this fact non printed material
	 */
	public void setCreatedByUserName(String createdByUserName);

	/**
	 * Returns the created by user ID of this fact non printed material.
	 *
	 * @return the created by user ID of this fact non printed material
	 */
	public long getCreatedByUserId();

	/**
	 * Sets the created by user ID of this fact non printed material.
	 *
	 * @param createdByUserId the created by user ID of this fact non printed material
	 */
	public void setCreatedByUserId(long createdByUserId);

	/**
	 * Returns the created by user uuid of this fact non printed material.
	 *
	 * @return the created by user uuid of this fact non printed material
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreatedByUserUuid() throws SystemException;

	/**
	 * Sets the created by user uuid of this fact non printed material.
	 *
	 * @param createdByUserUuid the created by user uuid of this fact non printed material
	 */
	public void setCreatedByUserUuid(String createdByUserUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.idetronic.eis.model.FactNonPrintedMaterial factNonPrintedMaterial);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.FactNonPrintedMaterial> toCacheModel();

	@Override
	public com.idetronic.eis.model.FactNonPrintedMaterial toEscapedModel();

	@Override
	public com.idetronic.eis.model.FactNonPrintedMaterial toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}