/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FactIrItem service. Represents a row in the &quot;eis_FactIrItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.FactIrItemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.FactIrItemImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see FactIrItem
 * @see com.idetronic.eis.model.impl.FactIrItemImpl
 * @see com.idetronic.eis.model.impl.FactIrItemModelImpl
 * @generated
 */
public interface FactIrItemModel extends BaseModel<FactIrItem> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fact ir item model instance should use the {@link FactIrItem} interface instead.
	 */

	/**
	 * Returns the primary key of this fact ir item.
	 *
	 * @return the primary key of this fact ir item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fact ir item.
	 *
	 * @param primaryKey the primary key of this fact ir item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the fact ir item ID of this fact ir item.
	 *
	 * @return the fact ir item ID of this fact ir item
	 */
	public long getFactIrItemId();

	/**
	 * Sets the fact ir item ID of this fact ir item.
	 *
	 * @param factIrItemId the fact ir item ID of this fact ir item
	 */
	public void setFactIrItemId(long factIrItemId);

	/**
	 * Returns the library ID of this fact ir item.
	 *
	 * @return the library ID of this fact ir item
	 */
	public long getLibraryId();

	/**
	 * Sets the library ID of this fact ir item.
	 *
	 * @param libraryId the library ID of this fact ir item
	 */
	public void setLibraryId(long libraryId);

	/**
	 * Returns the faculty ID of this fact ir item.
	 *
	 * @return the faculty ID of this fact ir item
	 */
	public long getFacultyId();

	/**
	 * Sets the faculty ID of this fact ir item.
	 *
	 * @param facultyId the faculty ID of this fact ir item
	 */
	public void setFacultyId(long facultyId);

	/**
	 * Returns the period of this fact ir item.
	 *
	 * @return the period of this fact ir item
	 */
	@AutoEscape
	public String getPeriod();

	/**
	 * Sets the period of this fact ir item.
	 *
	 * @param period the period of this fact ir item
	 */
	public void setPeriod(String period);

	/**
	 * Returns the item type ID of this fact ir item.
	 *
	 * @return the item type ID of this fact ir item
	 */
	public long getItemTypeId();

	/**
	 * Sets the item type ID of this fact ir item.
	 *
	 * @param itemTypeId the item type ID of this fact ir item
	 */
	public void setItemTypeId(long itemTypeId);

	/**
	 * Returns the item medium ID of this fact ir item.
	 *
	 * @return the item medium ID of this fact ir item
	 */
	public long getItemMediumId();

	/**
	 * Sets the item medium ID of this fact ir item.
	 *
	 * @param itemMediumId the item medium ID of this fact ir item
	 */
	public void setItemMediumId(long itemMediumId);

	/**
	 * Returns the title total of this fact ir item.
	 *
	 * @return the title total of this fact ir item
	 */
	public int getTitleTotal();

	/**
	 * Sets the title total of this fact ir item.
	 *
	 * @param titleTotal the title total of this fact ir item
	 */
	public void setTitleTotal(int titleTotal);

	/**
	 * Returns the volume total of this fact ir item.
	 *
	 * @return the volume total of this fact ir item
	 */
	public int getVolumeTotal();

	/**
	 * Sets the volume total of this fact ir item.
	 *
	 * @param volumeTotal the volume total of this fact ir item
	 */
	public void setVolumeTotal(int volumeTotal);

	/**
	 * Returns the created by user ID of this fact ir item.
	 *
	 * @return the created by user ID of this fact ir item
	 */
	public long getCreatedByUserId();

	/**
	 * Sets the created by user ID of this fact ir item.
	 *
	 * @param createdByUserId the created by user ID of this fact ir item
	 */
	public void setCreatedByUserId(long createdByUserId);

	/**
	 * Returns the created by user uuid of this fact ir item.
	 *
	 * @return the created by user uuid of this fact ir item
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreatedByUserUuid() throws SystemException;

	/**
	 * Sets the created by user uuid of this fact ir item.
	 *
	 * @param createdByUserUuid the created by user uuid of this fact ir item
	 */
	public void setCreatedByUserUuid(String createdByUserUuid);

	/**
	 * Returns the created by user name of this fact ir item.
	 *
	 * @return the created by user name of this fact ir item
	 */
	@AutoEscape
	public String getCreatedByUserName();

	/**
	 * Sets the created by user name of this fact ir item.
	 *
	 * @param createdByUserName the created by user name of this fact ir item
	 */
	public void setCreatedByUserName(String createdByUserName);

	/**
	 * Returns the created date of this fact ir item.
	 *
	 * @return the created date of this fact ir item
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this fact ir item.
	 *
	 * @param createdDate the created date of this fact ir item
	 */
	public void setCreatedDate(Date createdDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.eis.model.FactIrItem factIrItem);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.FactIrItem> toCacheModel();

	@Override
	public com.idetronic.eis.model.FactIrItem toEscapedModel();

	@Override
	public com.idetronic.eis.model.FactIrItem toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}