/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Faculty service. Represents a row in the &quot;eis_Faculty&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.FacultyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.FacultyImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see Faculty
 * @see com.idetronic.eis.model.impl.FacultyImpl
 * @see com.idetronic.eis.model.impl.FacultyModelImpl
 * @generated
 */
public interface FacultyModel extends BaseModel<Faculty> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a faculty model instance should use the {@link Faculty} interface instead.
	 */

	/**
	 * Returns the primary key of this faculty.
	 *
	 * @return the primary key of this faculty
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this faculty.
	 *
	 * @param primaryKey the primary key of this faculty
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the faculty ID of this faculty.
	 *
	 * @return the faculty ID of this faculty
	 */
	public long getFacultyId();

	/**
	 * Sets the faculty ID of this faculty.
	 *
	 * @param facultyId the faculty ID of this faculty
	 */
	public void setFacultyId(long facultyId);

	/**
	 * Returns the faculty type ID of this faculty.
	 *
	 * @return the faculty type ID of this faculty
	 */
	public long getFacultyTypeId();

	/**
	 * Sets the faculty type ID of this faculty.
	 *
	 * @param facultyTypeId the faculty type ID of this faculty
	 */
	public void setFacultyTypeId(long facultyTypeId);

	/**
	 * Returns the faculty name of this faculty.
	 *
	 * @return the faculty name of this faculty
	 */
	@AutoEscape
	public String getFacultyName();

	/**
	 * Sets the faculty name of this faculty.
	 *
	 * @param facultyName the faculty name of this faculty
	 */
	public void setFacultyName(String facultyName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.eis.model.Faculty faculty);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.Faculty> toCacheModel();

	@Override
	public com.idetronic.eis.model.Faculty toEscapedModel();

	@Override
	public com.idetronic.eis.model.Faculty toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}