/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ItemTypeCategory service. Represents a row in the &quot;eis_ItemTypeCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.ItemTypeCategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.ItemTypeCategoryImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see ItemTypeCategory
 * @see com.idetronic.eis.model.impl.ItemTypeCategoryImpl
 * @see com.idetronic.eis.model.impl.ItemTypeCategoryModelImpl
 * @generated
 */
public interface ItemTypeCategoryModel extends BaseModel<ItemTypeCategory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a item type category model instance should use the {@link ItemTypeCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this item type category.
	 *
	 * @return the primary key of this item type category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this item type category.
	 *
	 * @param primaryKey the primary key of this item type category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the item type category ID of this item type category.
	 *
	 * @return the item type category ID of this item type category
	 */
	public long getItemTypeCategoryId();

	/**
	 * Sets the item type category ID of this item type category.
	 *
	 * @param itemTypeCategoryId the item type category ID of this item type category
	 */
	public void setItemTypeCategoryId(long itemTypeCategoryId);

	/**
	 * Returns the item type category name of this item type category.
	 *
	 * @return the item type category name of this item type category
	 */
	@AutoEscape
	public String getItemTypeCategoryName();

	/**
	 * Sets the item type category name of this item type category.
	 *
	 * @param itemTypeCategoryName the item type category name of this item type category
	 */
	public void setItemTypeCategoryName(String itemTypeCategoryName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.idetronic.eis.model.ItemTypeCategory itemTypeCategory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.ItemTypeCategory> toCacheModel();

	@Override
	public com.idetronic.eis.model.ItemTypeCategory toEscapedModel();

	@Override
	public com.idetronic.eis.model.ItemTypeCategory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}