/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the KpiEntry service. Represents a row in the &quot;eis_KpiEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.KpiEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.KpiEntryImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see KpiEntry
 * @see com.idetronic.eis.model.impl.KpiEntryImpl
 * @see com.idetronic.eis.model.impl.KpiEntryModelImpl
 * @generated
 */
public interface KpiEntryModel extends BaseModel<KpiEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a kpi entry model instance should use the {@link KpiEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this kpi entry.
	 *
	 * @return the primary key of this kpi entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this kpi entry.
	 *
	 * @param primaryKey the primary key of this kpi entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the kpi entry ID of this kpi entry.
	 *
	 * @return the kpi entry ID of this kpi entry
	 */
	public long getKpiEntryId();

	/**
	 * Sets the kpi entry ID of this kpi entry.
	 *
	 * @param kpiEntryId the kpi entry ID of this kpi entry
	 */
	public void setKpiEntryId(long kpiEntryId);

	/**
	 * Returns the kpi type ID of this kpi entry.
	 *
	 * @return the kpi type ID of this kpi entry
	 */
	public long getKpiTypeId();

	/**
	 * Sets the kpi type ID of this kpi entry.
	 *
	 * @param kpiTypeId the kpi type ID of this kpi entry
	 */
	public void setKpiTypeId(long kpiTypeId);

	/**
	 * Returns the period year of this kpi entry.
	 *
	 * @return the period year of this kpi entry
	 */
	@AutoEscape
	public String getPeriodYear();

	/**
	 * Sets the period year of this kpi entry.
	 *
	 * @param periodYear the period year of this kpi entry
	 */
	public void setPeriodYear(String periodYear);

	/**
	 * Returns the period type of this kpi entry.
	 *
	 * @return the period type of this kpi entry
	 */
	public int getPeriodType();

	/**
	 * Sets the period type of this kpi entry.
	 *
	 * @param periodType the period type of this kpi entry
	 */
	public void setPeriodType(int periodType);

	/**
	 * Returns the period of this kpi entry.
	 *
	 * @return the period of this kpi entry
	 */
	@AutoEscape
	public String getPeriod();

	/**
	 * Sets the period of this kpi entry.
	 *
	 * @param period the period of this kpi entry
	 */
	public void setPeriod(String period);

	/**
	 * Returns the value of this kpi entry.
	 *
	 * @return the value of this kpi entry
	 */
	public double getValue();

	/**
	 * Sets the value of this kpi entry.
	 *
	 * @param value the value of this kpi entry
	 */
	public void setValue(double value);

	/**
	 * Returns the actual of this kpi entry.
	 *
	 * @return the actual of this kpi entry
	 */
	public double getActual();

	/**
	 * Sets the actual of this kpi entry.
	 *
	 * @param actual the actual of this kpi entry
	 */
	public void setActual(double actual);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.eis.model.KpiEntry kpiEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.KpiEntry> toCacheModel();

	@Override
	public com.idetronic.eis.model.KpiEntry toEscapedModel();

	@Override
	public com.idetronic.eis.model.KpiEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}