/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Kpi service. Represents a row in the &quot;eis_Kpi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.KpiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.KpiImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see Kpi
 * @see com.idetronic.eis.model.impl.KpiImpl
 * @see com.idetronic.eis.model.impl.KpiModelImpl
 * @generated
 */
public interface KpiModel extends BaseModel<Kpi> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a kpi model instance should use the {@link Kpi} interface instead.
	 */

	/**
	 * Returns the primary key of this kpi.
	 *
	 * @return the primary key of this kpi
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this kpi.
	 *
	 * @param primaryKey the primary key of this kpi
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this kpi.
	 *
	 * @return the ID of this kpi
	 */
	public long getId();

	/**
	 * Sets the ID of this kpi.
	 *
	 * @param id the ID of this kpi
	 */
	public void setId(long id);

	/**
	 * Returns the key of this kpi.
	 *
	 * @return the key of this kpi
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this kpi.
	 *
	 * @param key the key of this kpi
	 */
	public void setKey(String key);

	/**
	 * Returns the kpi type of this kpi.
	 *
	 * @return the kpi type of this kpi
	 */
	public int getKpiType();

	/**
	 * Sets the kpi type of this kpi.
	 *
	 * @param kpiType the kpi type of this kpi
	 */
	public void setKpiType(int kpiType);

	/**
	 * Returns the value of this kpi.
	 *
	 * @return the value of this kpi
	 */
	public int getValue();

	/**
	 * Sets the value of this kpi.
	 *
	 * @param value the value of this kpi
	 */
	public void setValue(int value);

	/**
	 * Returns the description of this kpi.
	 *
	 * @return the description of this kpi
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this kpi.
	 *
	 * @param description the description of this kpi
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.eis.model.Kpi kpi);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.Kpi> toCacheModel();

	@Override
	public com.idetronic.eis.model.Kpi toEscapedModel();

	@Override
	public com.idetronic.eis.model.Kpi toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}