/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the KpiType service. Represents a row in the &quot;eis_KpiType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.KpiTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.KpiTypeImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see KpiType
 * @see com.idetronic.eis.model.impl.KpiTypeImpl
 * @see com.idetronic.eis.model.impl.KpiTypeModelImpl
 * @generated
 */
public interface KpiTypeModel extends BaseModel<KpiType> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a kpi type model instance should use the {@link KpiType} interface instead.
	 */

	/**
	 * Returns the primary key of this kpi type.
	 *
	 * @return the primary key of this kpi type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this kpi type.
	 *
	 * @param primaryKey the primary key of this kpi type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the kpi type ID of this kpi type.
	 *
	 * @return the kpi type ID of this kpi type
	 */
	public long getKpiTypeId();

	/**
	 * Sets the kpi type ID of this kpi type.
	 *
	 * @param kpiTypeId the kpi type ID of this kpi type
	 */
	public void setKpiTypeId(long kpiTypeId);

	/**
	 * Returns the kpi type key of this kpi type.
	 *
	 * @return the kpi type key of this kpi type
	 */
	@AutoEscape
	public String getKpiTypeKey();

	/**
	 * Sets the kpi type key of this kpi type.
	 *
	 * @param kpiTypeKey the kpi type key of this kpi type
	 */
	public void setKpiTypeKey(String kpiTypeKey);

	/**
	 * Returns the kpi name of this kpi type.
	 *
	 * @return the kpi name of this kpi type
	 */
	@AutoEscape
	public String getKpiName();

	/**
	 * Sets the kpi name of this kpi type.
	 *
	 * @param kpiName the kpi name of this kpi type
	 */
	public void setKpiName(String kpiName);

	/**
	 * Returns the period month of this kpi type.
	 *
	 * @return the period month of this kpi type
	 */
	public boolean getPeriodMonth();

	/**
	 * Returns <code>true</code> if this kpi type is period month.
	 *
	 * @return <code>true</code> if this kpi type is period month; <code>false</code> otherwise
	 */
	public boolean isPeriodMonth();

	/**
	 * Sets whether this kpi type is period month.
	 *
	 * @param periodMonth the period month of this kpi type
	 */
	public void setPeriodMonth(boolean periodMonth);

	/**
	 * Returns the period quarter of this kpi type.
	 *
	 * @return the period quarter of this kpi type
	 */
	public boolean getPeriodQuarter();

	/**
	 * Returns <code>true</code> if this kpi type is period quarter.
	 *
	 * @return <code>true</code> if this kpi type is period quarter; <code>false</code> otherwise
	 */
	public boolean isPeriodQuarter();

	/**
	 * Sets whether this kpi type is period quarter.
	 *
	 * @param periodQuarter the period quarter of this kpi type
	 */
	public void setPeriodQuarter(boolean periodQuarter);

	/**
	 * Returns the period semi annual of this kpi type.
	 *
	 * @return the period semi annual of this kpi type
	 */
	public boolean getPeriodSemiAnnual();

	/**
	 * Returns <code>true</code> if this kpi type is period semi annual.
	 *
	 * @return <code>true</code> if this kpi type is period semi annual; <code>false</code> otherwise
	 */
	public boolean isPeriodSemiAnnual();

	/**
	 * Sets whether this kpi type is period semi annual.
	 *
	 * @param periodSemiAnnual the period semi annual of this kpi type
	 */
	public void setPeriodSemiAnnual(boolean periodSemiAnnual);

	/**
	 * Returns the period year of this kpi type.
	 *
	 * @return the period year of this kpi type
	 */
	public boolean getPeriodYear();

	/**
	 * Returns <code>true</code> if this kpi type is period year.
	 *
	 * @return <code>true</code> if this kpi type is period year; <code>false</code> otherwise
	 */
	public boolean isPeriodYear();

	/**
	 * Sets whether this kpi type is period year.
	 *
	 * @param periodYear the period year of this kpi type
	 */
	public void setPeriodYear(boolean periodYear);

	/**
	 * Returns the is decimal of this kpi type.
	 *
	 * @return the is decimal of this kpi type
	 */
	public boolean getIsDecimal();

	/**
	 * Returns <code>true</code> if this kpi type is is decimal.
	 *
	 * @return <code>true</code> if this kpi type is is decimal; <code>false</code> otherwise
	 */
	public boolean isIsDecimal();

	/**
	 * Sets whether this kpi type is is decimal.
	 *
	 * @param isDecimal the is decimal of this kpi type
	 */
	public void setIsDecimal(boolean isDecimal);

	/**
	 * Returns the manual value of this kpi type.
	 *
	 * @return the manual value of this kpi type
	 */
	public boolean getManualValue();

	/**
	 * Returns <code>true</code> if this kpi type is manual value.
	 *
	 * @return <code>true</code> if this kpi type is manual value; <code>false</code> otherwise
	 */
	public boolean isManualValue();

	/**
	 * Sets whether this kpi type is manual value.
	 *
	 * @param manualValue the manual value of this kpi type
	 */
	public void setManualValue(boolean manualValue);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.eis.model.KpiType kpiType);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.KpiType> toCacheModel();

	@Override
	public com.idetronic.eis.model.KpiType toEscapedModel();

	@Override
	public com.idetronic.eis.model.KpiType toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}