/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LibraryType service. Represents a row in the &quot;eis_LibraryType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.LibraryTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.LibraryTypeImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see LibraryType
 * @see com.idetronic.eis.model.impl.LibraryTypeImpl
 * @see com.idetronic.eis.model.impl.LibraryTypeModelImpl
 * @generated
 */
public interface LibraryTypeModel extends BaseModel<LibraryType> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a library type model instance should use the {@link LibraryType} interface instead.
	 */

	/**
	 * Returns the primary key of this library type.
	 *
	 * @return the primary key of this library type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this library type.
	 *
	 * @param primaryKey the primary key of this library type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the library type ID of this library type.
	 *
	 * @return the library type ID of this library type
	 */
	public long getLibraryTypeId();

	/**
	 * Sets the library type ID of this library type.
	 *
	 * @param libraryTypeId the library type ID of this library type
	 */
	public void setLibraryTypeId(long libraryTypeId);

	/**
	 * Returns the library type code of this library type.
	 *
	 * @return the library type code of this library type
	 */
	@AutoEscape
	public String getLibraryTypeCode();

	/**
	 * Sets the library type code of this library type.
	 *
	 * @param libraryTypeCode the library type code of this library type
	 */
	public void setLibraryTypeCode(String libraryTypeCode);

	/**
	 * Returns the library type name of this library type.
	 *
	 * @return the library type name of this library type
	 */
	@AutoEscape
	public String getLibraryTypeName();

	/**
	 * Sets the library type name of this library type.
	 *
	 * @param libraryTypeName the library type name of this library type
	 */
	public void setLibraryTypeName(String libraryTypeName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.eis.model.LibraryType libraryType);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.LibraryType> toCacheModel();

	@Override
	public com.idetronic.eis.model.LibraryType toEscapedModel();

	@Override
	public com.idetronic.eis.model.LibraryType toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}