/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the library service. Represents a row in the &quot;eis_library&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.libraryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.libraryImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see library
 * @see com.idetronic.eis.model.impl.libraryImpl
 * @see com.idetronic.eis.model.impl.libraryModelImpl
 * @generated
 */
public interface libraryModel extends BaseModel<library>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a library model instance should use the {@link library} interface instead.
	 */

	/**
	 * Returns the primary key of this library.
	 *
	 * @return the primary key of this library
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this library.
	 *
	 * @param primaryKey the primary key of this library
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the library ID of this library.
	 *
	 * @return the library ID of this library
	 */
	public long getLibraryId();

	/**
	 * Sets the library ID of this library.
	 *
	 * @param libraryId the library ID of this library
	 */
	public void setLibraryId(long libraryId);

	/**
	 * Returns the library code of this library.
	 *
	 * @return the library code of this library
	 */
	@AutoEscape
	public String getLibraryCode();

	/**
	 * Sets the library code of this library.
	 *
	 * @param libraryCode the library code of this library
	 */
	public void setLibraryCode(String libraryCode);

	/**
	 * Returns the state code of this library.
	 *
	 * @return the state code of this library
	 */
	@AutoEscape
	public String getStateCode();

	/**
	 * Sets the state code of this library.
	 *
	 * @param stateCode the state code of this library
	 */
	public void setStateCode(String stateCode);

	/**
	 * Returns the library type ID of this library.
	 *
	 * @return the library type ID of this library
	 */
	public long getLibraryTypeId();

	/**
	 * Sets the library type ID of this library.
	 *
	 * @param libraryTypeId the library type ID of this library
	 */
	public void setLibraryTypeId(long libraryTypeId);

	/**
	 * Returns the state name of this library.
	 *
	 * @return the state name of this library
	 */
	@AutoEscape
	public String getStateName();

	/**
	 * Sets the state name of this library.
	 *
	 * @param stateName the state name of this library
	 */
	public void setStateName(String stateName);

	/**
	 * Returns the library name of this library.
	 *
	 * @return the library name of this library
	 */
	@AutoEscape
	public String getLibraryName();

	/**
	 * Sets the library name of this library.
	 *
	 * @param libraryName the library name of this library
	 */
	public void setLibraryName(String libraryName);

	/**
	 * Returns the company ID of this library.
	 *
	 * @return the company ID of this library
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this library.
	 *
	 * @param companyId the company ID of this library
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this library.
	 *
	 * @return the group ID of this library
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this library.
	 *
	 * @param groupId the group ID of this library
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this library.
	 *
	 * @return the user ID of this library
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this library.
	 *
	 * @param userId the user ID of this library
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this library.
	 *
	 * @return the user uuid of this library
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this library.
	 *
	 * @param userUuid the user uuid of this library
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this library.
	 *
	 * @return the user name of this library
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this library.
	 *
	 * @param userName the user name of this library
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this library.
	 *
	 * @return the create date of this library
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this library.
	 *
	 * @param createDate the create date of this library
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this library.
	 *
	 * @return the modified date of this library
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this library.
	 *
	 * @param modifiedDate the modified date of this library
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.eis.model.library library);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.library> toCacheModel();

	@Override
	public com.idetronic.eis.model.library toEscapedModel();

	@Override
	public com.idetronic.eis.model.library toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}