/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LibrarySeatingDepartment service. Represents a row in the &quot;eis_LibrarySeatingDepartment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.LibrarySeatingDepartmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.LibrarySeatingDepartmentImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see LibrarySeatingDepartment
 * @see com.idetronic.eis.model.impl.LibrarySeatingDepartmentImpl
 * @see com.idetronic.eis.model.impl.LibrarySeatingDepartmentModelImpl
 * @generated
 */
public interface LibrarySeatingDepartmentModel extends BaseModel<LibrarySeatingDepartment>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a library seating department model instance should use the {@link LibrarySeatingDepartment} interface instead.
	 */

	/**
	 * Returns the primary key of this library seating department.
	 *
	 * @return the primary key of this library seating department
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this library seating department.
	 *
	 * @param primaryKey the primary key of this library seating department
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the library department ID of this library seating department.
	 *
	 * @return the library department ID of this library seating department
	 */
	public long getLibraryDepartmentId();

	/**
	 * Sets the library department ID of this library seating department.
	 *
	 * @param libraryDepartmentId the library department ID of this library seating department
	 */
	public void setLibraryDepartmentId(long libraryDepartmentId);

	/**
	 * Returns the library ID of this library seating department.
	 *
	 * @return the library ID of this library seating department
	 */
	public long getLibraryId();

	/**
	 * Sets the library ID of this library seating department.
	 *
	 * @param libraryId the library ID of this library seating department
	 */
	public void setLibraryId(long libraryId);

	/**
	 * Returns the department ID of this library seating department.
	 *
	 * @return the department ID of this library seating department
	 */
	public long getDepartmentId();

	/**
	 * Sets the department ID of this library seating department.
	 *
	 * @param departmentId the department ID of this library seating department
	 */
	public void setDepartmentId(long departmentId);

	/**
	 * Returns the company ID of this library seating department.
	 *
	 * @return the company ID of this library seating department
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this library seating department.
	 *
	 * @param companyId the company ID of this library seating department
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this library seating department.
	 *
	 * @return the group ID of this library seating department
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this library seating department.
	 *
	 * @param groupId the group ID of this library seating department
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this library seating department.
	 *
	 * @return the user ID of this library seating department
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this library seating department.
	 *
	 * @param userId the user ID of this library seating department
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this library seating department.
	 *
	 * @return the user uuid of this library seating department
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this library seating department.
	 *
	 * @param userUuid the user uuid of this library seating department
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this library seating department.
	 *
	 * @return the user name of this library seating department
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this library seating department.
	 *
	 * @param userName the user name of this library seating department
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this library seating department.
	 *
	 * @return the create date of this library seating department
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this library seating department.
	 *
	 * @param createDate the create date of this library seating department
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this library seating department.
	 *
	 * @return the modified date of this library seating department
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this library seating department.
	 *
	 * @param modifiedDate the modified date of this library seating department
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.idetronic.eis.model.LibrarySeatingDepartment librarySeatingDepartment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.LibrarySeatingDepartment> toCacheModel();

	@Override
	public com.idetronic.eis.model.LibrarySeatingDepartment toEscapedModel();

	@Override
	public com.idetronic.eis.model.LibrarySeatingDepartment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}