/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Loan service. Represents a row in the &quot;eis_Loan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.LoanModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.LoanImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see Loan
 * @see com.idetronic.eis.model.impl.LoanImpl
 * @see com.idetronic.eis.model.impl.LoanModelImpl
 * @generated
 */
public interface LoanModel extends BaseModel<Loan> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a loan model instance should use the {@link Loan} interface instead.
	 */

	/**
	 * Returns the primary key of this loan.
	 *
	 * @return the primary key of this loan
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this loan.
	 *
	 * @param primaryKey the primary key of this loan
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the loan entry ID of this loan.
	 *
	 * @return the loan entry ID of this loan
	 */
	public long getLoanEntryId();

	/**
	 * Sets the loan entry ID of this loan.
	 *
	 * @param loanEntryId the loan entry ID of this loan
	 */
	public void setLoanEntryId(long loanEntryId);

	/**
	 * Returns the library ID of this loan.
	 *
	 * @return the library ID of this loan
	 */
	public long getLibraryId();

	/**
	 * Sets the library ID of this loan.
	 *
	 * @param libraryId the library ID of this loan
	 */
	public void setLibraryId(long libraryId);

	/**
	 * Returns the user ID of this loan.
	 *
	 * @return the user ID of this loan
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this loan.
	 *
	 * @param userId the user ID of this loan
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this loan.
	 *
	 * @return the user uuid of this loan
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this loan.
	 *
	 * @param userUuid the user uuid of this loan
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this loan.
	 *
	 * @return the user name of this loan
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this loan.
	 *
	 * @param userName the user name of this loan
	 */
	public void setUserName(String userName);

	/**
	 * Returns the period of this loan.
	 *
	 * @return the period of this loan
	 */
	@AutoEscape
	public String getPeriod();

	/**
	 * Sets the period of this loan.
	 *
	 * @param period the period of this loan
	 */
	public void setPeriod(String period);

	/**
	 * Returns the state ID of this loan.
	 *
	 * @return the state ID of this loan
	 */
	public long getStateId();

	/**
	 * Sets the state ID of this loan.
	 *
	 * @param stateId the state ID of this loan
	 */
	public void setStateId(long stateId);

	/**
	 * Returns the library type ID of this loan.
	 *
	 * @return the library type ID of this loan
	 */
	public long getLibraryTypeId();

	/**
	 * Sets the library type ID of this loan.
	 *
	 * @param libraryTypeId the library type ID of this loan
	 */
	public void setLibraryTypeId(long libraryTypeId);

	/**
	 * Returns the period year of this loan.
	 *
	 * @return the period year of this loan
	 */
	public int getPeriodYear();

	/**
	 * Sets the period year of this loan.
	 *
	 * @param periodYear the period year of this loan
	 */
	public void setPeriodYear(int periodYear);

	/**
	 * Returns the period month of this loan.
	 *
	 * @return the period month of this loan
	 */
	public int getPeriodMonth();

	/**
	 * Sets the period month of this loan.
	 *
	 * @param periodMonth the period month of this loan
	 */
	public void setPeriodMonth(int periodMonth);

	/**
	 * Returns the create date of this loan.
	 *
	 * @return the create date of this loan
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this loan.
	 *
	 * @param createDate the create date of this loan
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the member category ID of this loan.
	 *
	 * @return the member category ID of this loan
	 */
	public long getMemberCategoryId();

	/**
	 * Sets the member category ID of this loan.
	 *
	 * @param memberCategoryId the member category ID of this loan
	 */
	public void setMemberCategoryId(long memberCategoryId);

	/**
	 * Returns the value of this loan.
	 *
	 * @return the value of this loan
	 */
	public int getValue();

	/**
	 * Sets the value of this loan.
	 *
	 * @param value the value of this loan
	 */
	public void setValue(int value);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.eis.model.Loan loan);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.Loan> toCacheModel();

	@Override
	public com.idetronic.eis.model.Loan toEscapedModel();

	@Override
	public com.idetronic.eis.model.Loan toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}