/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PostGrade service. Represents a row in the &quot;eis_PostGrade&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.PostGradeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.PostGradeImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see PostGrade
 * @see com.idetronic.eis.model.impl.PostGradeImpl
 * @see com.idetronic.eis.model.impl.PostGradeModelImpl
 * @generated
 */
public interface PostGradeModel extends BaseModel<PostGrade>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a post grade model instance should use the {@link PostGrade} interface instead.
	 */

	/**
	 * Returns the primary key of this post grade.
	 *
	 * @return the primary key of this post grade
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this post grade.
	 *
	 * @param primaryKey the primary key of this post grade
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the post grade ID of this post grade.
	 *
	 * @return the post grade ID of this post grade
	 */
	public long getPostGradeId();

	/**
	 * Sets the post grade ID of this post grade.
	 *
	 * @param postGradeId the post grade ID of this post grade
	 */
	public void setPostGradeId(long postGradeId);

	/**
	 * Returns the post category ID of this post grade.
	 *
	 * @return the post category ID of this post grade
	 */
	public long getPostCategoryId();

	/**
	 * Sets the post category ID of this post grade.
	 *
	 * @param postCategoryId the post category ID of this post grade
	 */
	public void setPostCategoryId(long postCategoryId);

	/**
	 * Returns the post grade code of this post grade.
	 *
	 * @return the post grade code of this post grade
	 */
	@AutoEscape
	public String getPostGradeCode();

	/**
	 * Sets the post grade code of this post grade.
	 *
	 * @param postGradeCode the post grade code of this post grade
	 */
	public void setPostGradeCode(String postGradeCode);

	/**
	 * Returns the post grade scheme of this post grade.
	 *
	 * @return the post grade scheme of this post grade
	 */
	@AutoEscape
	public String getPostGradeScheme();

	/**
	 * Sets the post grade scheme of this post grade.
	 *
	 * @param postGradeScheme the post grade scheme of this post grade
	 */
	public void setPostGradeScheme(String postGradeScheme);

	/**
	 * Returns the post grade name of this post grade.
	 *
	 * @return the post grade name of this post grade
	 */
	@AutoEscape
	public String getPostGradeName();

	/**
	 * Sets the post grade name of this post grade.
	 *
	 * @param postGradeName the post grade name of this post grade
	 */
	public void setPostGradeName(String postGradeName);

	/**
	 * Returns the post grade desc of this post grade.
	 *
	 * @return the post grade desc of this post grade
	 */
	@AutoEscape
	public String getPostGradeDesc();

	/**
	 * Sets the post grade desc of this post grade.
	 *
	 * @param postGradeDesc the post grade desc of this post grade
	 */
	public void setPostGradeDesc(String postGradeDesc);

	/**
	 * Returns the company ID of this post grade.
	 *
	 * @return the company ID of this post grade
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this post grade.
	 *
	 * @param companyId the company ID of this post grade
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this post grade.
	 *
	 * @return the group ID of this post grade
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this post grade.
	 *
	 * @param groupId the group ID of this post grade
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this post grade.
	 *
	 * @return the user ID of this post grade
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this post grade.
	 *
	 * @param userId the user ID of this post grade
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this post grade.
	 *
	 * @return the user uuid of this post grade
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this post grade.
	 *
	 * @param userUuid the user uuid of this post grade
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this post grade.
	 *
	 * @return the user name of this post grade
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this post grade.
	 *
	 * @param userName the user name of this post grade
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this post grade.
	 *
	 * @return the create date of this post grade
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this post grade.
	 *
	 * @param createDate the create date of this post grade
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this post grade.
	 *
	 * @return the modified date of this post grade
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this post grade.
	 *
	 * @param modifiedDate the modified date of this post grade
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.eis.model.PostGrade postGrade);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.PostGrade> toCacheModel();

	@Override
	public com.idetronic.eis.model.PostGrade toEscapedModel();

	@Override
	public com.idetronic.eis.model.PostGrade toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}