/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PostCategory service. Represents a row in the &quot;eis_PostCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.PostCategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.PostCategoryImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see PostCategory
 * @see com.idetronic.eis.model.impl.PostCategoryImpl
 * @see com.idetronic.eis.model.impl.PostCategoryModelImpl
 * @generated
 */
public interface PostCategoryModel extends BaseModel<PostCategory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a post category model instance should use the {@link PostCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this post category.
	 *
	 * @return the primary key of this post category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this post category.
	 *
	 * @param primaryKey the primary key of this post category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the post category ID of this post category.
	 *
	 * @return the post category ID of this post category
	 */
	public long getPostCategoryId();

	/**
	 * Sets the post category ID of this post category.
	 *
	 * @param postCategoryId the post category ID of this post category
	 */
	public void setPostCategoryId(long postCategoryId);

	/**
	 * Returns the post category code of this post category.
	 *
	 * @return the post category code of this post category
	 */
	@AutoEscape
	public String getPostCategoryCode();

	/**
	 * Sets the post category code of this post category.
	 *
	 * @param postCategoryCode the post category code of this post category
	 */
	public void setPostCategoryCode(String postCategoryCode);

	/**
	 * Returns the post category name of this post category.
	 *
	 * @return the post category name of this post category
	 */
	@AutoEscape
	public String getPostCategoryName();

	/**
	 * Sets the post category name of this post category.
	 *
	 * @param postCategoryName the post category name of this post category
	 */
	public void setPostCategoryName(String postCategoryName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.eis.model.PostCategory postCategory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.PostCategory> toCacheModel();

	@Override
	public com.idetronic.eis.model.PostCategory toEscapedModel();

	@Override
	public com.idetronic.eis.model.PostCategory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}