/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PrintedItemType service. Represents a row in the &quot;eis_PrintedItemType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.PrintedItemTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.PrintedItemTypeImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see PrintedItemType
 * @see com.idetronic.eis.model.impl.PrintedItemTypeImpl
 * @see com.idetronic.eis.model.impl.PrintedItemTypeModelImpl
 * @generated
 */
public interface PrintedItemTypeModel extends BaseModel<PrintedItemType> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a printed item type model instance should use the {@link PrintedItemType} interface instead.
	 */

	/**
	 * Returns the primary key of this printed item type.
	 *
	 * @return the primary key of this printed item type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this printed item type.
	 *
	 * @param primaryKey the primary key of this printed item type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the item type ID of this printed item type.
	 *
	 * @return the item type ID of this printed item type
	 */
	public long getItemTypeId();

	/**
	 * Sets the item type ID of this printed item type.
	 *
	 * @param itemTypeId the item type ID of this printed item type
	 */
	public void setItemTypeId(long itemTypeId);

	/**
	 * Returns the item type name of this printed item type.
	 *
	 * @return the item type name of this printed item type
	 */
	@AutoEscape
	public String getItemTypeName();

	/**
	 * Sets the item type name of this printed item type.
	 *
	 * @param itemTypeName the item type name of this printed item type
	 */
	public void setItemTypeName(String itemTypeName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.idetronic.eis.model.PrintedItemType printedItemType);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.PrintedItemType> toCacheModel();

	@Override
	public com.idetronic.eis.model.PrintedItemType toEscapedModel();

	@Override
	public com.idetronic.eis.model.PrintedItemType toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}