/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ProjectResourceType service. Represents a row in the &quot;eis_ProjectResourceType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.ProjectResourceTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.ProjectResourceTypeImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see ProjectResourceType
 * @see com.idetronic.eis.model.impl.ProjectResourceTypeImpl
 * @see com.idetronic.eis.model.impl.ProjectResourceTypeModelImpl
 * @generated
 */
public interface ProjectResourceTypeModel extends BaseModel<ProjectResourceType>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project resource type model instance should use the {@link ProjectResourceType} interface instead.
	 */

	/**
	 * Returns the primary key of this project resource type.
	 *
	 * @return the primary key of this project resource type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this project resource type.
	 *
	 * @param primaryKey the primary key of this project resource type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the project resource type ID of this project resource type.
	 *
	 * @return the project resource type ID of this project resource type
	 */
	public long getProjectResourceTypeId();

	/**
	 * Sets the project resource type ID of this project resource type.
	 *
	 * @param projectResourceTypeId the project resource type ID of this project resource type
	 */
	public void setProjectResourceTypeId(long projectResourceTypeId);

	/**
	 * Returns the resource type name of this project resource type.
	 *
	 * @return the resource type name of this project resource type
	 */
	@AutoEscape
	public String getResourceTypeName();

	/**
	 * Sets the resource type name of this project resource type.
	 *
	 * @param resourceTypeName the resource type name of this project resource type
	 */
	public void setResourceTypeName(String resourceTypeName);

	/**
	 * Returns the group ID of this project resource type.
	 *
	 * @return the group ID of this project resource type
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this project resource type.
	 *
	 * @param groupId the group ID of this project resource type
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this project resource type.
	 *
	 * @return the company ID of this project resource type
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this project resource type.
	 *
	 * @param companyId the company ID of this project resource type
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this project resource type.
	 *
	 * @return the user ID of this project resource type
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this project resource type.
	 *
	 * @param userId the user ID of this project resource type
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this project resource type.
	 *
	 * @return the user uuid of this project resource type
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this project resource type.
	 *
	 * @param userUuid the user uuid of this project resource type
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this project resource type.
	 *
	 * @return the user name of this project resource type
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this project resource type.
	 *
	 * @param userName the user name of this project resource type
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this project resource type.
	 *
	 * @return the create date of this project resource type
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this project resource type.
	 *
	 * @param createDate the create date of this project resource type
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this project resource type.
	 *
	 * @return the modified date of this project resource type
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this project resource type.
	 *
	 * @param modifiedDate the modified date of this project resource type
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.idetronic.eis.model.ProjectResourceType projectResourceType);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.ProjectResourceType> toCacheModel();

	@Override
	public com.idetronic.eis.model.ProjectResourceType toEscapedModel();

	@Override
	public com.idetronic.eis.model.ProjectResourceType toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}