/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Project service. Represents a row in the &quot;eis_Project&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.ProjectModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.ProjectImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see Project
 * @see com.idetronic.eis.model.impl.ProjectImpl
 * @see com.idetronic.eis.model.impl.ProjectModelImpl
 * @generated
 */
public interface ProjectModel extends BaseModel<Project>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project model instance should use the {@link Project} interface instead.
	 */

	/**
	 * Returns the primary key of this project.
	 *
	 * @return the primary key of this project
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this project.
	 *
	 * @param primaryKey the primary key of this project
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the project ID of this project.
	 *
	 * @return the project ID of this project
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this project.
	 *
	 * @param projectId the project ID of this project
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the project name of this project.
	 *
	 * @return the project name of this project
	 */
	@AutoEscape
	public String getProjectName();

	/**
	 * Sets the project name of this project.
	 *
	 * @param projectName the project name of this project
	 */
	public void setProjectName(String projectName);

	/**
	 * Returns the project status of this project.
	 *
	 * @return the project status of this project
	 */
	public int getProjectStatus();

	/**
	 * Sets the project status of this project.
	 *
	 * @param projectStatus the project status of this project
	 */
	public void setProjectStatus(int projectStatus);

	/**
	 * Returns the start date of this project.
	 *
	 * @return the start date of this project
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this project.
	 *
	 * @param startDate the start date of this project
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this project.
	 *
	 * @return the end date of this project
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this project.
	 *
	 * @param endDate the end date of this project
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the start month of this project.
	 *
	 * @return the start month of this project
	 */
	public int getStartMonth();

	/**
	 * Sets the start month of this project.
	 *
	 * @param startMonth the start month of this project
	 */
	public void setStartMonth(int startMonth);

	/**
	 * Returns the start year of this project.
	 *
	 * @return the start year of this project
	 */
	public int getStartYear();

	/**
	 * Sets the start year of this project.
	 *
	 * @param startYear the start year of this project
	 */
	public void setStartYear(int startYear);

	/**
	 * Returns the start month name of this project.
	 *
	 * @return the start month name of this project
	 */
	@AutoEscape
	public String getStartMonthName();

	/**
	 * Sets the start month name of this project.
	 *
	 * @param startMonthName the start month name of this project
	 */
	public void setStartMonthName(String startMonthName);

	/**
	 * Returns the end month of this project.
	 *
	 * @return the end month of this project
	 */
	public int getEndMonth();

	/**
	 * Sets the end month of this project.
	 *
	 * @param endMonth the end month of this project
	 */
	public void setEndMonth(int endMonth);

	/**
	 * Returns the end year of this project.
	 *
	 * @return the end year of this project
	 */
	public int getEndYear();

	/**
	 * Sets the end year of this project.
	 *
	 * @param endYear the end year of this project
	 */
	public void setEndYear(int endYear);

	/**
	 * Returns the progress status of this project.
	 *
	 * @return the progress status of this project
	 */
	public int getProgressStatus();

	/**
	 * Sets the progress status of this project.
	 *
	 * @param progressStatus the progress status of this project
	 */
	public void setProgressStatus(int progressStatus);

	/**
	 * Returns the end month name of this project.
	 *
	 * @return the end month name of this project
	 */
	@AutoEscape
	public String getEndMonthName();

	/**
	 * Sets the end month name of this project.
	 *
	 * @param endMonthName the end month name of this project
	 */
	public void setEndMonthName(String endMonthName);

	/**
	 * Returns the completion date of this project.
	 *
	 * @return the completion date of this project
	 */
	public Date getCompletionDate();

	/**
	 * Sets the completion date of this project.
	 *
	 * @param completionDate the completion date of this project
	 */
	public void setCompletionDate(Date completionDate);

	/**
	 * Returns the progress of this project.
	 *
	 * @return the progress of this project
	 */
	public int getProgress();

	/**
	 * Sets the progress of this project.
	 *
	 * @param progress the progress of this project
	 */
	public void setProgress(int progress);

	/**
	 * Returns the resource ID of this project.
	 *
	 * @return the resource ID of this project
	 */
	public long getResourceId();

	/**
	 * Sets the resource ID of this project.
	 *
	 * @param resourceId the resource ID of this project
	 */
	public void setResourceId(long resourceId);

	/**
	 * Returns the resource type ID of this project.
	 *
	 * @return the resource type ID of this project
	 */
	public long getResourceTypeId();

	/**
	 * Sets the resource type ID of this project.
	 *
	 * @param resourceTypeId the resource type ID of this project
	 */
	public void setResourceTypeId(long resourceTypeId);

	/**
	 * Returns the resource name of this project.
	 *
	 * @return the resource name of this project
	 */
	@AutoEscape
	public String getResourceName();

	/**
	 * Sets the resource name of this project.
	 *
	 * @param resourceName the resource name of this project
	 */
	public void setResourceName(String resourceName);

	/**
	 * Returns the resource type of this project.
	 *
	 * @return the resource type of this project
	 */
	@AutoEscape
	public String getResourceType();

	/**
	 * Sets the resource type of this project.
	 *
	 * @param resourceType the resource type of this project
	 */
	public void setResourceType(String resourceType);

	/**
	 * Returns the group ID of this project.
	 *
	 * @return the group ID of this project
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this project.
	 *
	 * @param groupId the group ID of this project
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this project.
	 *
	 * @return the company ID of this project
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this project.
	 *
	 * @param companyId the company ID of this project
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this project.
	 *
	 * @return the user ID of this project
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this project.
	 *
	 * @param userId the user ID of this project
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this project.
	 *
	 * @return the user uuid of this project
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this project.
	 *
	 * @param userUuid the user uuid of this project
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this project.
	 *
	 * @return the user name of this project
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this project.
	 *
	 * @param userName the user name of this project
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this project.
	 *
	 * @return the create date of this project
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this project.
	 *
	 * @param createDate the create date of this project
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this project.
	 *
	 * @return the modified date of this project
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this project.
	 *
	 * @param modifiedDate the modified date of this project
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.eis.model.Project project);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.Project> toCacheModel();

	@Override
	public com.idetronic.eis.model.Project toEscapedModel();

	@Override
	public com.idetronic.eis.model.Project toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}