/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SeatingCategory service. Represents a row in the &quot;eis_SeatingCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.SeatingCategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.SeatingCategoryImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see SeatingCategory
 * @see com.idetronic.eis.model.impl.SeatingCategoryImpl
 * @see com.idetronic.eis.model.impl.SeatingCategoryModelImpl
 * @generated
 */
public interface SeatingCategoryModel extends BaseModel<SeatingCategory>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a seating category model instance should use the {@link SeatingCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this seating category.
	 *
	 * @return the primary key of this seating category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this seating category.
	 *
	 * @param primaryKey the primary key of this seating category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the seating category ID of this seating category.
	 *
	 * @return the seating category ID of this seating category
	 */
	public long getSeatingCategoryId();

	/**
	 * Sets the seating category ID of this seating category.
	 *
	 * @param seatingCategoryId the seating category ID of this seating category
	 */
	public void setSeatingCategoryId(long seatingCategoryId);

	/**
	 * Returns the seating category name of this seating category.
	 *
	 * @return the seating category name of this seating category
	 */
	@AutoEscape
	public String getSeatingCategoryName();

	/**
	 * Sets the seating category name of this seating category.
	 *
	 * @param seatingCategoryName the seating category name of this seating category
	 */
	public void setSeatingCategoryName(String seatingCategoryName);

	/**
	 * Returns the seating department ID of this seating category.
	 *
	 * @return the seating department ID of this seating category
	 */
	public long getSeatingDepartmentId();

	/**
	 * Sets the seating department ID of this seating category.
	 *
	 * @param seatingDepartmentId the seating department ID of this seating category
	 */
	public void setSeatingDepartmentId(long seatingDepartmentId);

	/**
	 * Returns the company ID of this seating category.
	 *
	 * @return the company ID of this seating category
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this seating category.
	 *
	 * @param companyId the company ID of this seating category
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this seating category.
	 *
	 * @return the group ID of this seating category
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this seating category.
	 *
	 * @param groupId the group ID of this seating category
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this seating category.
	 *
	 * @return the user ID of this seating category
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this seating category.
	 *
	 * @param userId the user ID of this seating category
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this seating category.
	 *
	 * @return the user uuid of this seating category
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this seating category.
	 *
	 * @param userUuid the user uuid of this seating category
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this seating category.
	 *
	 * @return the user name of this seating category
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this seating category.
	 *
	 * @param userName the user name of this seating category
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this seating category.
	 *
	 * @return the create date of this seating category
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this seating category.
	 *
	 * @param createDate the create date of this seating category
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this seating category.
	 *
	 * @return the modified date of this seating category
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this seating category.
	 *
	 * @param modifiedDate the modified date of this seating category
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.idetronic.eis.model.SeatingCategory seatingCategory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.SeatingCategory> toCacheModel();

	@Override
	public com.idetronic.eis.model.SeatingCategory toEscapedModel();

	@Override
	public com.idetronic.eis.model.SeatingCategory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}