/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserData service. Represents a row in the &quot;eis_UserData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.UserDataModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.UserDataImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see UserData
 * @see com.idetronic.eis.model.impl.UserDataImpl
 * @see com.idetronic.eis.model.impl.UserDataModelImpl
 * @generated
 */
public interface UserDataModel extends BaseModel<UserData> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user data model instance should use the {@link UserData} interface instead.
	 */

	/**
	 * Returns the primary key of this user data.
	 *
	 * @return the primary key of this user data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user data.
	 *
	 * @param primaryKey the primary key of this user data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user data ID of this user data.
	 *
	 * @return the user data ID of this user data
	 */
	public long getUserDataId();

	/**
	 * Sets the user data ID of this user data.
	 *
	 * @param userDataId the user data ID of this user data
	 */
	public void setUserDataId(long userDataId);

	/**
	 * Returns the user ID of this user data.
	 *
	 * @return the user ID of this user data
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user data.
	 *
	 * @param userId the user ID of this user data
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user data.
	 *
	 * @return the user uuid of this user data
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this user data.
	 *
	 * @param userUuid the user uuid of this user data
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the library ID of this user data.
	 *
	 * @return the library ID of this user data
	 */
	public long getLibraryId();

	/**
	 * Sets the library ID of this user data.
	 *
	 * @param libraryId the library ID of this user data
	 */
	public void setLibraryId(long libraryId);

	/**
	 * Returns the data ID of this user data.
	 *
	 * @return the data ID of this user data
	 */
	public long getDataId();

	/**
	 * Sets the data ID of this user data.
	 *
	 * @param dataId the data ID of this user data
	 */
	public void setDataId(long dataId);

	/**
	 * Returns the created by user ID of this user data.
	 *
	 * @return the created by user ID of this user data
	 */
	public long getCreatedByUserId();

	/**
	 * Sets the created by user ID of this user data.
	 *
	 * @param createdByUserId the created by user ID of this user data
	 */
	public void setCreatedByUserId(long createdByUserId);

	/**
	 * Returns the created by user uuid of this user data.
	 *
	 * @return the created by user uuid of this user data
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreatedByUserUuid() throws SystemException;

	/**
	 * Sets the created by user uuid of this user data.
	 *
	 * @param createdByUserUuid the created by user uuid of this user data
	 */
	public void setCreatedByUserUuid(String createdByUserUuid);

	/**
	 * Returns the user name of this user data.
	 *
	 * @return the user name of this user data
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this user data.
	 *
	 * @param userName the user name of this user data
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this user data.
	 *
	 * @return the create date of this user data
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this user data.
	 *
	 * @param createDate the create date of this user data
	 */
	public void setCreateDate(Date createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.eis.model.UserData userData);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.UserData> toCacheModel();

	@Override
	public com.idetronic.eis.model.UserData toEscapedModel();

	@Override
	public com.idetronic.eis.model.UserData toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}