/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserLibrary service. Represents a row in the &quot;eis_UserLibrary&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.UserLibraryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.UserLibraryImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see UserLibrary
 * @see com.idetronic.eis.model.impl.UserLibraryImpl
 * @see com.idetronic.eis.model.impl.UserLibraryModelImpl
 * @generated
 */
public interface UserLibraryModel extends BaseModel<UserLibrary>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user library model instance should use the {@link UserLibrary} interface instead.
	 */

	/**
	 * Returns the primary key of this user library.
	 *
	 * @return the primary key of this user library
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user library.
	 *
	 * @param primaryKey the primary key of this user library
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user library ID of this user library.
	 *
	 * @return the user library ID of this user library
	 */
	public long getUserLibraryId();

	/**
	 * Sets the user library ID of this user library.
	 *
	 * @param userLibraryId the user library ID of this user library
	 */
	public void setUserLibraryId(long userLibraryId);

	/**
	 * Returns the user ID of this user library.
	 *
	 * @return the user ID of this user library
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this user library.
	 *
	 * @param userId the user ID of this user library
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user library.
	 *
	 * @return the user uuid of this user library
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this user library.
	 *
	 * @param userUuid the user uuid of this user library
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the library ID of this user library.
	 *
	 * @return the library ID of this user library
	 */
	public long getLibraryId();

	/**
	 * Sets the library ID of this user library.
	 *
	 * @param libraryId the library ID of this user library
	 */
	public void setLibraryId(long libraryId);

	/**
	 * Returns the company ID of this user library.
	 *
	 * @return the company ID of this user library
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this user library.
	 *
	 * @param companyId the company ID of this user library
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this user library.
	 *
	 * @return the group ID of this user library
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this user library.
	 *
	 * @param groupId the group ID of this user library
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the created by user ID of this user library.
	 *
	 * @return the created by user ID of this user library
	 */
	public long getCreatedByUserId();

	/**
	 * Sets the created by user ID of this user library.
	 *
	 * @param createdByUserId the created by user ID of this user library
	 */
	public void setCreatedByUserId(long createdByUserId);

	/**
	 * Returns the created by user uuid of this user library.
	 *
	 * @return the created by user uuid of this user library
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreatedByUserUuid() throws SystemException;

	/**
	 * Sets the created by user uuid of this user library.
	 *
	 * @param createdByUserUuid the created by user uuid of this user library
	 */
	public void setCreatedByUserUuid(String createdByUserUuid);

	/**
	 * Returns the user name of this user library.
	 *
	 * @return the user name of this user library
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this user library.
	 *
	 * @param userName the user name of this user library
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this user library.
	 *
	 * @return the create date of this user library
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this user library.
	 *
	 * @param createDate the create date of this user library
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user library.
	 *
	 * @return the modified date of this user library
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user library.
	 *
	 * @param modifiedDate the modified date of this user library
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.eis.model.UserLibrary userLibrary);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.UserLibrary> toCacheModel();

	@Override
	public com.idetronic.eis.model.UserLibrary toEscapedModel();

	@Override
	public com.idetronic.eis.model.UserLibrary toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}