/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserReport service. Represents a row in the &quot;eis_UserReport&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eis.model.impl.UserReportModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eis.model.impl.UserReportImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see UserReport
 * @see com.idetronic.eis.model.impl.UserReportImpl
 * @see com.idetronic.eis.model.impl.UserReportModelImpl
 * @generated
 */
public interface UserReportModel extends BaseModel<UserReport> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user report model instance should use the {@link UserReport} interface instead.
	 */

	/**
	 * Returns the primary key of this user report.
	 *
	 * @return the primary key of this user report
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user report.
	 *
	 * @param primaryKey the primary key of this user report
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user report ID of this user report.
	 *
	 * @return the user report ID of this user report
	 */
	public long getUserReportId();

	/**
	 * Sets the user report ID of this user report.
	 *
	 * @param userReportId the user report ID of this user report
	 */
	public void setUserReportId(long userReportId);

	/**
	 * Returns the user ID of this user report.
	 *
	 * @return the user ID of this user report
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user report.
	 *
	 * @param userId the user ID of this user report
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user report.
	 *
	 * @return the user uuid of this user report
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this user report.
	 *
	 * @param userUuid the user uuid of this user report
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the library ID of this user report.
	 *
	 * @return the library ID of this user report
	 */
	public long getLibraryId();

	/**
	 * Sets the library ID of this user report.
	 *
	 * @param libraryId the library ID of this user report
	 */
	public void setLibraryId(long libraryId);

	/**
	 * Returns the report ID of this user report.
	 *
	 * @return the report ID of this user report
	 */
	public long getReportId();

	/**
	 * Sets the report ID of this user report.
	 *
	 * @param reportId the report ID of this user report
	 */
	public void setReportId(long reportId);

	/**
	 * Returns the created by user ID of this user report.
	 *
	 * @return the created by user ID of this user report
	 */
	public long getCreatedByUserId();

	/**
	 * Sets the created by user ID of this user report.
	 *
	 * @param createdByUserId the created by user ID of this user report
	 */
	public void setCreatedByUserId(long createdByUserId);

	/**
	 * Returns the created by user uuid of this user report.
	 *
	 * @return the created by user uuid of this user report
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreatedByUserUuid() throws SystemException;

	/**
	 * Sets the created by user uuid of this user report.
	 *
	 * @param createdByUserUuid the created by user uuid of this user report
	 */
	public void setCreatedByUserUuid(String createdByUserUuid);

	/**
	 * Returns the user name of this user report.
	 *
	 * @return the user name of this user report
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this user report.
	 *
	 * @param userName the user name of this user report
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this user report.
	 *
	 * @return the create date of this user report
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this user report.
	 *
	 * @param createDate the create date of this user report
	 */
	public void setCreateDate(Date createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.eis.model.UserReport userReport);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.eis.model.UserReport> toCacheModel();

	@Override
	public com.idetronic.eis.model.UserReport toEscapedModel();

	@Override
	public com.idetronic.eis.model.UserReport toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}