/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model.impl;

import com.idetronic.eis.model.FactCustomerComplaint;
import com.idetronic.eis.model.FactCustomerComplaintModel;
import com.idetronic.eis.model.FactCustomerComplaintSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the FactCustomerComplaint service. Represents a row in the &quot;eis_FactCustomerComplaint&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.idetronic.eis.model.FactCustomerComplaintModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FactCustomerComplaintImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see FactCustomerComplaintImpl
 * @see com.idetronic.eis.model.FactCustomerComplaint
 * @see com.idetronic.eis.model.FactCustomerComplaintModel
 * @generated
 */
@JSON(strict = true)
public class FactCustomerComplaintModelImpl extends BaseModelImpl<FactCustomerComplaint>
	implements FactCustomerComplaintModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fact customer complaint model instance should use the {@link com.idetronic.eis.model.FactCustomerComplaint} interface instead.
	 */
	public static final String TABLE_NAME = "eis_FactCustomerComplaint";
	public static final Object[][] TABLE_COLUMNS = {
			{ "factId", Types.BIGINT },
			{ "libraryId", Types.BIGINT },
			{ "period", Types.VARCHAR },
			{ "complaintTotal", Types.BIGINT },
			{ "unsettledTotal", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table eis_FactCustomerComplaint (factId LONG not null primary key,libraryId LONG,period VARCHAR(75) null,complaintTotal LONG,unsettledTotal LONG,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table eis_FactCustomerComplaint";
	public static final String ORDER_BY_JPQL = " ORDER BY factCustomerComplaint.factId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY eis_FactCustomerComplaint.factId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.idetronic.eis.model.FactCustomerComplaint"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.idetronic.eis.model.FactCustomerComplaint"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static FactCustomerComplaint toModel(
		FactCustomerComplaintSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		FactCustomerComplaint model = new FactCustomerComplaintImpl();

		model.setFactId(soapModel.getFactId());
		model.setLibraryId(soapModel.getLibraryId());
		model.setPeriod(soapModel.getPeriod());
		model.setComplaintTotal(soapModel.getComplaintTotal());
		model.setUnsettledTotal(soapModel.getUnsettledTotal());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<FactCustomerComplaint> toModels(
		FactCustomerComplaintSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<FactCustomerComplaint> models = new ArrayList<FactCustomerComplaint>(soapModels.length);

		for (FactCustomerComplaintSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.idetronic.eis.model.FactCustomerComplaint"));

	public FactCustomerComplaintModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _factId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFactId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _factId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FactCustomerComplaint.class;
	}

	@Override
	public String getModelClassName() {
		return FactCustomerComplaint.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("factId", getFactId());
		attributes.put("libraryId", getLibraryId());
		attributes.put("period", getPeriod());
		attributes.put("complaintTotal", getComplaintTotal());
		attributes.put("unsettledTotal", getUnsettledTotal());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long factId = (Long)attributes.get("factId");

		if (factId != null) {
			setFactId(factId);
		}

		Long libraryId = (Long)attributes.get("libraryId");

		if (libraryId != null) {
			setLibraryId(libraryId);
		}

		String period = (String)attributes.get("period");

		if (period != null) {
			setPeriod(period);
		}

		Long complaintTotal = (Long)attributes.get("complaintTotal");

		if (complaintTotal != null) {
			setComplaintTotal(complaintTotal);
		}

		Long unsettledTotal = (Long)attributes.get("unsettledTotal");

		if (unsettledTotal != null) {
			setUnsettledTotal(unsettledTotal);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}
	}

	@JSON
	@Override
	public long getFactId() {
		return _factId;
	}

	@Override
	public void setFactId(long factId) {
		_factId = factId;
	}

	@JSON
	@Override
	public long getLibraryId() {
		return _libraryId;
	}

	@Override
	public void setLibraryId(long libraryId) {
		_libraryId = libraryId;
	}

	@JSON
	@Override
	public String getPeriod() {
		if (_period == null) {
			return StringPool.BLANK;
		}
		else {
			return _period;
		}
	}

	@Override
	public void setPeriod(String period) {
		_period = period;
	}

	@JSON
	@Override
	public long getComplaintTotal() {
		return _complaintTotal;
	}

	@Override
	public void setComplaintTotal(long complaintTotal) {
		_complaintTotal = complaintTotal;
	}

	@JSON
	@Override
	public long getUnsettledTotal() {
		return _unsettledTotal;
	}

	@Override
	public void setUnsettledTotal(long unsettledTotal) {
		_unsettledTotal = unsettledTotal;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			FactCustomerComplaint.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FactCustomerComplaint toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (FactCustomerComplaint)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FactCustomerComplaintImpl factCustomerComplaintImpl = new FactCustomerComplaintImpl();

		factCustomerComplaintImpl.setFactId(getFactId());
		factCustomerComplaintImpl.setLibraryId(getLibraryId());
		factCustomerComplaintImpl.setPeriod(getPeriod());
		factCustomerComplaintImpl.setComplaintTotal(getComplaintTotal());
		factCustomerComplaintImpl.setUnsettledTotal(getUnsettledTotal());
		factCustomerComplaintImpl.setCompanyId(getCompanyId());
		factCustomerComplaintImpl.setGroupId(getGroupId());
		factCustomerComplaintImpl.setUserId(getUserId());
		factCustomerComplaintImpl.setUserName(getUserName());
		factCustomerComplaintImpl.setCreateDate(getCreateDate());

		factCustomerComplaintImpl.resetOriginalValues();

		return factCustomerComplaintImpl;
	}

	@Override
	public int compareTo(FactCustomerComplaint factCustomerComplaint) {
		long primaryKey = factCustomerComplaint.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof FactCustomerComplaint)) {
			return false;
		}

		FactCustomerComplaint factCustomerComplaint = (FactCustomerComplaint)obj;

		long primaryKey = factCustomerComplaint.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<FactCustomerComplaint> toCacheModel() {
		FactCustomerComplaintCacheModel factCustomerComplaintCacheModel = new FactCustomerComplaintCacheModel();

		factCustomerComplaintCacheModel.factId = getFactId();

		factCustomerComplaintCacheModel.libraryId = getLibraryId();

		factCustomerComplaintCacheModel.period = getPeriod();

		String period = factCustomerComplaintCacheModel.period;

		if ((period != null) && (period.length() == 0)) {
			factCustomerComplaintCacheModel.period = null;
		}

		factCustomerComplaintCacheModel.complaintTotal = getComplaintTotal();

		factCustomerComplaintCacheModel.unsettledTotal = getUnsettledTotal();

		factCustomerComplaintCacheModel.companyId = getCompanyId();

		factCustomerComplaintCacheModel.groupId = getGroupId();

		factCustomerComplaintCacheModel.userId = getUserId();

		factCustomerComplaintCacheModel.userName = getUserName();

		String userName = factCustomerComplaintCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			factCustomerComplaintCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			factCustomerComplaintCacheModel.createDate = createDate.getTime();
		}
		else {
			factCustomerComplaintCacheModel.createDate = Long.MIN_VALUE;
		}

		return factCustomerComplaintCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{factId=");
		sb.append(getFactId());
		sb.append(", libraryId=");
		sb.append(getLibraryId());
		sb.append(", period=");
		sb.append(getPeriod());
		sb.append(", complaintTotal=");
		sb.append(getComplaintTotal());
		sb.append(", unsettledTotal=");
		sb.append(getUnsettledTotal());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.idetronic.eis.model.FactCustomerComplaint");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>factId</column-name><column-value><![CDATA[");
		sb.append(getFactId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>libraryId</column-name><column-value><![CDATA[");
		sb.append(getLibraryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>period</column-name><column-value><![CDATA[");
		sb.append(getPeriod());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>complaintTotal</column-name><column-value><![CDATA[");
		sb.append(getComplaintTotal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>unsettledTotal</column-name><column-value><![CDATA[");
		sb.append(getUnsettledTotal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = FactCustomerComplaint.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			FactCustomerComplaint.class
		};
	private long _factId;
	private long _libraryId;
	private String _period;
	private long _complaintTotal;
	private long _unsettledTotal;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private FactCustomerComplaint _escapedModel;
}