/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model.impl;

import com.idetronic.eis.model.FactIrItem;
import com.idetronic.eis.model.FactIrItemModel;
import com.idetronic.eis.model.FactIrItemSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the FactIrItem service. Represents a row in the &quot;eis_FactIrItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.idetronic.eis.model.FactIrItemModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FactIrItemImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see FactIrItemImpl
 * @see com.idetronic.eis.model.FactIrItem
 * @see com.idetronic.eis.model.FactIrItemModel
 * @generated
 */
@JSON(strict = true)
public class FactIrItemModelImpl extends BaseModelImpl<FactIrItem>
	implements FactIrItemModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fact ir item model instance should use the {@link com.idetronic.eis.model.FactIrItem} interface instead.
	 */
	public static final String TABLE_NAME = "eis_FactIrItem";
	public static final Object[][] TABLE_COLUMNS = {
			{ "factIrItemId", Types.BIGINT },
			{ "libraryId", Types.BIGINT },
			{ "facultyId", Types.BIGINT },
			{ "period", Types.VARCHAR },
			{ "itemTypeId", Types.BIGINT },
			{ "itemMediumId", Types.BIGINT },
			{ "titleTotal", Types.INTEGER },
			{ "volumeTotal", Types.INTEGER },
			{ "createdByUserId", Types.BIGINT },
			{ "createdByUserName", Types.VARCHAR },
			{ "createdDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table eis_FactIrItem (factIrItemId LONG not null primary key,libraryId LONG,facultyId LONG,period VARCHAR(10) null,itemTypeId LONG,itemMediumId LONG,titleTotal INTEGER,volumeTotal INTEGER,createdByUserId LONG,createdByUserName VARCHAR(75) null,createdDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table eis_FactIrItem";
	public static final String ORDER_BY_JPQL = " ORDER BY factIrItem.factIrItemId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY eis_FactIrItem.factIrItemId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.idetronic.eis.model.FactIrItem"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.idetronic.eis.model.FactIrItem"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.idetronic.eis.model.FactIrItem"),
			true);
	public static long FACULTYID_COLUMN_BITMASK = 1L;
	public static long ITEMMEDIUMID_COLUMN_BITMASK = 2L;
	public static long ITEMTYPEID_COLUMN_BITMASK = 4L;
	public static long LIBRARYID_COLUMN_BITMASK = 8L;
	public static long PERIOD_COLUMN_BITMASK = 16L;
	public static long FACTIRITEMID_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static FactIrItem toModel(FactIrItemSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		FactIrItem model = new FactIrItemImpl();

		model.setFactIrItemId(soapModel.getFactIrItemId());
		model.setLibraryId(soapModel.getLibraryId());
		model.setFacultyId(soapModel.getFacultyId());
		model.setPeriod(soapModel.getPeriod());
		model.setItemTypeId(soapModel.getItemTypeId());
		model.setItemMediumId(soapModel.getItemMediumId());
		model.setTitleTotal(soapModel.getTitleTotal());
		model.setVolumeTotal(soapModel.getVolumeTotal());
		model.setCreatedByUserId(soapModel.getCreatedByUserId());
		model.setCreatedByUserName(soapModel.getCreatedByUserName());
		model.setCreatedDate(soapModel.getCreatedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<FactIrItem> toModels(FactIrItemSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<FactIrItem> models = new ArrayList<FactIrItem>(soapModels.length);

		for (FactIrItemSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.idetronic.eis.model.FactIrItem"));

	public FactIrItemModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _factIrItemId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFactIrItemId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _factIrItemId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FactIrItem.class;
	}

	@Override
	public String getModelClassName() {
		return FactIrItem.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("factIrItemId", getFactIrItemId());
		attributes.put("libraryId", getLibraryId());
		attributes.put("facultyId", getFacultyId());
		attributes.put("period", getPeriod());
		attributes.put("itemTypeId", getItemTypeId());
		attributes.put("itemMediumId", getItemMediumId());
		attributes.put("titleTotal", getTitleTotal());
		attributes.put("volumeTotal", getVolumeTotal());
		attributes.put("createdByUserId", getCreatedByUserId());
		attributes.put("createdByUserName", getCreatedByUserName());
		attributes.put("createdDate", getCreatedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long factIrItemId = (Long)attributes.get("factIrItemId");

		if (factIrItemId != null) {
			setFactIrItemId(factIrItemId);
		}

		Long libraryId = (Long)attributes.get("libraryId");

		if (libraryId != null) {
			setLibraryId(libraryId);
		}

		Long facultyId = (Long)attributes.get("facultyId");

		if (facultyId != null) {
			setFacultyId(facultyId);
		}

		String period = (String)attributes.get("period");

		if (period != null) {
			setPeriod(period);
		}

		Long itemTypeId = (Long)attributes.get("itemTypeId");

		if (itemTypeId != null) {
			setItemTypeId(itemTypeId);
		}

		Long itemMediumId = (Long)attributes.get("itemMediumId");

		if (itemMediumId != null) {
			setItemMediumId(itemMediumId);
		}

		Integer titleTotal = (Integer)attributes.get("titleTotal");

		if (titleTotal != null) {
			setTitleTotal(titleTotal);
		}

		Integer volumeTotal = (Integer)attributes.get("volumeTotal");

		if (volumeTotal != null) {
			setVolumeTotal(volumeTotal);
		}

		Long createdByUserId = (Long)attributes.get("createdByUserId");

		if (createdByUserId != null) {
			setCreatedByUserId(createdByUserId);
		}

		String createdByUserName = (String)attributes.get("createdByUserName");

		if (createdByUserName != null) {
			setCreatedByUserName(createdByUserName);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}
	}

	@JSON
	@Override
	public long getFactIrItemId() {
		return _factIrItemId;
	}

	@Override
	public void setFactIrItemId(long factIrItemId) {
		_factIrItemId = factIrItemId;
	}

	@JSON
	@Override
	public long getLibraryId() {
		return _libraryId;
	}

	@Override
	public void setLibraryId(long libraryId) {
		_columnBitmask |= LIBRARYID_COLUMN_BITMASK;

		if (!_setOriginalLibraryId) {
			_setOriginalLibraryId = true;

			_originalLibraryId = _libraryId;
		}

		_libraryId = libraryId;
	}

	public long getOriginalLibraryId() {
		return _originalLibraryId;
	}

	@JSON
	@Override
	public long getFacultyId() {
		return _facultyId;
	}

	@Override
	public void setFacultyId(long facultyId) {
		_columnBitmask |= FACULTYID_COLUMN_BITMASK;

		if (!_setOriginalFacultyId) {
			_setOriginalFacultyId = true;

			_originalFacultyId = _facultyId;
		}

		_facultyId = facultyId;
	}

	public long getOriginalFacultyId() {
		return _originalFacultyId;
	}

	@JSON
	@Override
	public String getPeriod() {
		if (_period == null) {
			return StringPool.BLANK;
		}
		else {
			return _period;
		}
	}

	@Override
	public void setPeriod(String period) {
		_columnBitmask |= PERIOD_COLUMN_BITMASK;

		if (_originalPeriod == null) {
			_originalPeriod = _period;
		}

		_period = period;
	}

	public String getOriginalPeriod() {
		return GetterUtil.getString(_originalPeriod);
	}

	@JSON
	@Override
	public long getItemTypeId() {
		return _itemTypeId;
	}

	@Override
	public void setItemTypeId(long itemTypeId) {
		_columnBitmask |= ITEMTYPEID_COLUMN_BITMASK;

		if (!_setOriginalItemTypeId) {
			_setOriginalItemTypeId = true;

			_originalItemTypeId = _itemTypeId;
		}

		_itemTypeId = itemTypeId;
	}

	public long getOriginalItemTypeId() {
		return _originalItemTypeId;
	}

	@JSON
	@Override
	public long getItemMediumId() {
		return _itemMediumId;
	}

	@Override
	public void setItemMediumId(long itemMediumId) {
		_columnBitmask |= ITEMMEDIUMID_COLUMN_BITMASK;

		if (!_setOriginalItemMediumId) {
			_setOriginalItemMediumId = true;

			_originalItemMediumId = _itemMediumId;
		}

		_itemMediumId = itemMediumId;
	}

	public long getOriginalItemMediumId() {
		return _originalItemMediumId;
	}

	@JSON
	@Override
	public int getTitleTotal() {
		return _titleTotal;
	}

	@Override
	public void setTitleTotal(int titleTotal) {
		_titleTotal = titleTotal;
	}

	@JSON
	@Override
	public int getVolumeTotal() {
		return _volumeTotal;
	}

	@Override
	public void setVolumeTotal(int volumeTotal) {
		_volumeTotal = volumeTotal;
	}

	@JSON
	@Override
	public long getCreatedByUserId() {
		return _createdByUserId;
	}

	@Override
	public void setCreatedByUserId(long createdByUserId) {
		_createdByUserId = createdByUserId;
	}

	@Override
	public String getCreatedByUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getCreatedByUserId(), "uuid",
			_createdByUserUuid);
	}

	@Override
	public void setCreatedByUserUuid(String createdByUserUuid) {
		_createdByUserUuid = createdByUserUuid;
	}

	@JSON
	@Override
	public String getCreatedByUserName() {
		if (_createdByUserName == null) {
			return StringPool.BLANK;
		}
		else {
			return _createdByUserName;
		}
	}

	@Override
	public void setCreatedByUserName(String createdByUserName) {
		_createdByUserName = createdByUserName;
	}

	@JSON
	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			FactIrItem.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FactIrItem toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (FactIrItem)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FactIrItemImpl factIrItemImpl = new FactIrItemImpl();

		factIrItemImpl.setFactIrItemId(getFactIrItemId());
		factIrItemImpl.setLibraryId(getLibraryId());
		factIrItemImpl.setFacultyId(getFacultyId());
		factIrItemImpl.setPeriod(getPeriod());
		factIrItemImpl.setItemTypeId(getItemTypeId());
		factIrItemImpl.setItemMediumId(getItemMediumId());
		factIrItemImpl.setTitleTotal(getTitleTotal());
		factIrItemImpl.setVolumeTotal(getVolumeTotal());
		factIrItemImpl.setCreatedByUserId(getCreatedByUserId());
		factIrItemImpl.setCreatedByUserName(getCreatedByUserName());
		factIrItemImpl.setCreatedDate(getCreatedDate());

		factIrItemImpl.resetOriginalValues();

		return factIrItemImpl;
	}

	@Override
	public int compareTo(FactIrItem factIrItem) {
		long primaryKey = factIrItem.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof FactIrItem)) {
			return false;
		}

		FactIrItem factIrItem = (FactIrItem)obj;

		long primaryKey = factIrItem.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		FactIrItemModelImpl factIrItemModelImpl = this;

		factIrItemModelImpl._originalLibraryId = factIrItemModelImpl._libraryId;

		factIrItemModelImpl._setOriginalLibraryId = false;

		factIrItemModelImpl._originalFacultyId = factIrItemModelImpl._facultyId;

		factIrItemModelImpl._setOriginalFacultyId = false;

		factIrItemModelImpl._originalPeriod = factIrItemModelImpl._period;

		factIrItemModelImpl._originalItemTypeId = factIrItemModelImpl._itemTypeId;

		factIrItemModelImpl._setOriginalItemTypeId = false;

		factIrItemModelImpl._originalItemMediumId = factIrItemModelImpl._itemMediumId;

		factIrItemModelImpl._setOriginalItemMediumId = false;

		factIrItemModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<FactIrItem> toCacheModel() {
		FactIrItemCacheModel factIrItemCacheModel = new FactIrItemCacheModel();

		factIrItemCacheModel.factIrItemId = getFactIrItemId();

		factIrItemCacheModel.libraryId = getLibraryId();

		factIrItemCacheModel.facultyId = getFacultyId();

		factIrItemCacheModel.period = getPeriod();

		String period = factIrItemCacheModel.period;

		if ((period != null) && (period.length() == 0)) {
			factIrItemCacheModel.period = null;
		}

		factIrItemCacheModel.itemTypeId = getItemTypeId();

		factIrItemCacheModel.itemMediumId = getItemMediumId();

		factIrItemCacheModel.titleTotal = getTitleTotal();

		factIrItemCacheModel.volumeTotal = getVolumeTotal();

		factIrItemCacheModel.createdByUserId = getCreatedByUserId();

		factIrItemCacheModel.createdByUserName = getCreatedByUserName();

		String createdByUserName = factIrItemCacheModel.createdByUserName;

		if ((createdByUserName != null) && (createdByUserName.length() == 0)) {
			factIrItemCacheModel.createdByUserName = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			factIrItemCacheModel.createdDate = createdDate.getTime();
		}
		else {
			factIrItemCacheModel.createdDate = Long.MIN_VALUE;
		}

		return factIrItemCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{factIrItemId=");
		sb.append(getFactIrItemId());
		sb.append(", libraryId=");
		sb.append(getLibraryId());
		sb.append(", facultyId=");
		sb.append(getFacultyId());
		sb.append(", period=");
		sb.append(getPeriod());
		sb.append(", itemTypeId=");
		sb.append(getItemTypeId());
		sb.append(", itemMediumId=");
		sb.append(getItemMediumId());
		sb.append(", titleTotal=");
		sb.append(getTitleTotal());
		sb.append(", volumeTotal=");
		sb.append(getVolumeTotal());
		sb.append(", createdByUserId=");
		sb.append(getCreatedByUserId());
		sb.append(", createdByUserName=");
		sb.append(getCreatedByUserName());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.idetronic.eis.model.FactIrItem");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>factIrItemId</column-name><column-value><![CDATA[");
		sb.append(getFactIrItemId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>libraryId</column-name><column-value><![CDATA[");
		sb.append(getLibraryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>facultyId</column-name><column-value><![CDATA[");
		sb.append(getFacultyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>period</column-name><column-value><![CDATA[");
		sb.append(getPeriod());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>itemTypeId</column-name><column-value><![CDATA[");
		sb.append(getItemTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>itemMediumId</column-name><column-value><![CDATA[");
		sb.append(getItemMediumId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>titleTotal</column-name><column-value><![CDATA[");
		sb.append(getTitleTotal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>volumeTotal</column-name><column-value><![CDATA[");
		sb.append(getVolumeTotal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdByUserId</column-name><column-value><![CDATA[");
		sb.append(getCreatedByUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdByUserName</column-name><column-value><![CDATA[");
		sb.append(getCreatedByUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = FactIrItem.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			FactIrItem.class
		};
	private long _factIrItemId;
	private long _libraryId;
	private long _originalLibraryId;
	private boolean _setOriginalLibraryId;
	private long _facultyId;
	private long _originalFacultyId;
	private boolean _setOriginalFacultyId;
	private String _period;
	private String _originalPeriod;
	private long _itemTypeId;
	private long _originalItemTypeId;
	private boolean _setOriginalItemTypeId;
	private long _itemMediumId;
	private long _originalItemMediumId;
	private boolean _setOriginalItemMediumId;
	private int _titleTotal;
	private int _volumeTotal;
	private long _createdByUserId;
	private String _createdByUserUuid;
	private String _createdByUserName;
	private Date _createdDate;
	private long _columnBitmask;
	private FactIrItem _escapedModel;
}