/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model.impl;

import com.idetronic.eis.model.FactData;
import com.idetronic.eis.model.FactDataModel;
import com.idetronic.eis.model.FactDataSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the FactData service. Represents a row in the &quot;eis_FactData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.idetronic.eis.model.FactDataModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FactDataImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see FactDataImpl
 * @see com.idetronic.eis.model.FactData
 * @see com.idetronic.eis.model.FactDataModel
 * @generated
 */
@JSON(strict = true)
public class FactDataModelImpl extends BaseModelImpl<FactData>
	implements FactDataModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fact data model instance should use the {@link com.idetronic.eis.model.FactData} interface instead.
	 */
	public static final String TABLE_NAME = "eis_FactData";
	public static final Object[][] TABLE_COLUMNS = {
			{ "factId", Types.BIGINT },
			{ "reportId", Types.BIGINT },
			{ "libraryId", Types.BIGINT },
			{ "period", Types.VARCHAR },
			{ "dimensionId", Types.BIGINT },
			{ "measure1", Types.DOUBLE },
			{ "measure2", Types.DOUBLE },
			{ "measure3", Types.DOUBLE },
			{ "measure4", Types.DOUBLE },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table eis_FactData (factId LONG not null primary key,reportId LONG,libraryId LONG,period VARCHAR(75) null,dimensionId LONG,measure1 DOUBLE,measure2 DOUBLE,measure3 DOUBLE,measure4 DOUBLE,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table eis_FactData";
	public static final String ORDER_BY_JPQL = " ORDER BY factData.factId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY eis_FactData.factId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.idetronic.eis.model.FactData"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.idetronic.eis.model.FactData"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static FactData toModel(FactDataSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		FactData model = new FactDataImpl();

		model.setFactId(soapModel.getFactId());
		model.setReportId(soapModel.getReportId());
		model.setLibraryId(soapModel.getLibraryId());
		model.setPeriod(soapModel.getPeriod());
		model.setDimensionId(soapModel.getDimensionId());
		model.setMeasure1(soapModel.getMeasure1());
		model.setMeasure2(soapModel.getMeasure2());
		model.setMeasure3(soapModel.getMeasure3());
		model.setMeasure4(soapModel.getMeasure4());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<FactData> toModels(FactDataSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<FactData> models = new ArrayList<FactData>(soapModels.length);

		for (FactDataSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.idetronic.eis.model.FactData"));

	public FactDataModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _factId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFactId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _factId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FactData.class;
	}

	@Override
	public String getModelClassName() {
		return FactData.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("factId", getFactId());
		attributes.put("reportId", getReportId());
		attributes.put("libraryId", getLibraryId());
		attributes.put("period", getPeriod());
		attributes.put("dimensionId", getDimensionId());
		attributes.put("measure1", getMeasure1());
		attributes.put("measure2", getMeasure2());
		attributes.put("measure3", getMeasure3());
		attributes.put("measure4", getMeasure4());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long factId = (Long)attributes.get("factId");

		if (factId != null) {
			setFactId(factId);
		}

		Long reportId = (Long)attributes.get("reportId");

		if (reportId != null) {
			setReportId(reportId);
		}

		Long libraryId = (Long)attributes.get("libraryId");

		if (libraryId != null) {
			setLibraryId(libraryId);
		}

		String period = (String)attributes.get("period");

		if (period != null) {
			setPeriod(period);
		}

		Long dimensionId = (Long)attributes.get("dimensionId");

		if (dimensionId != null) {
			setDimensionId(dimensionId);
		}

		Double measure1 = (Double)attributes.get("measure1");

		if (measure1 != null) {
			setMeasure1(measure1);
		}

		Double measure2 = (Double)attributes.get("measure2");

		if (measure2 != null) {
			setMeasure2(measure2);
		}

		Double measure3 = (Double)attributes.get("measure3");

		if (measure3 != null) {
			setMeasure3(measure3);
		}

		Double measure4 = (Double)attributes.get("measure4");

		if (measure4 != null) {
			setMeasure4(measure4);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}
	}

	@JSON
	@Override
	public long getFactId() {
		return _factId;
	}

	@Override
	public void setFactId(long factId) {
		_factId = factId;
	}

	@JSON
	@Override
	public long getReportId() {
		return _reportId;
	}

	@Override
	public void setReportId(long reportId) {
		_reportId = reportId;
	}

	@JSON
	@Override
	public long getLibraryId() {
		return _libraryId;
	}

	@Override
	public void setLibraryId(long libraryId) {
		_libraryId = libraryId;
	}

	@JSON
	@Override
	public String getPeriod() {
		if (_period == null) {
			return StringPool.BLANK;
		}
		else {
			return _period;
		}
	}

	@Override
	public void setPeriod(String period) {
		_period = period;
	}

	@JSON
	@Override
	public long getDimensionId() {
		return _dimensionId;
	}

	@Override
	public void setDimensionId(long dimensionId) {
		_dimensionId = dimensionId;
	}

	@JSON
	@Override
	public double getMeasure1() {
		return _measure1;
	}

	@Override
	public void setMeasure1(double measure1) {
		_measure1 = measure1;
	}

	@JSON
	@Override
	public double getMeasure2() {
		return _measure2;
	}

	@Override
	public void setMeasure2(double measure2) {
		_measure2 = measure2;
	}

	@JSON
	@Override
	public double getMeasure3() {
		return _measure3;
	}

	@Override
	public void setMeasure3(double measure3) {
		_measure3 = measure3;
	}

	@JSON
	@Override
	public double getMeasure4() {
		return _measure4;
	}

	@Override
	public void setMeasure4(double measure4) {
		_measure4 = measure4;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			FactData.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FactData toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (FactData)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FactDataImpl factDataImpl = new FactDataImpl();

		factDataImpl.setFactId(getFactId());
		factDataImpl.setReportId(getReportId());
		factDataImpl.setLibraryId(getLibraryId());
		factDataImpl.setPeriod(getPeriod());
		factDataImpl.setDimensionId(getDimensionId());
		factDataImpl.setMeasure1(getMeasure1());
		factDataImpl.setMeasure2(getMeasure2());
		factDataImpl.setMeasure3(getMeasure3());
		factDataImpl.setMeasure4(getMeasure4());
		factDataImpl.setCompanyId(getCompanyId());
		factDataImpl.setGroupId(getGroupId());
		factDataImpl.setUserId(getUserId());
		factDataImpl.setUserName(getUserName());
		factDataImpl.setCreateDate(getCreateDate());

		factDataImpl.resetOriginalValues();

		return factDataImpl;
	}

	@Override
	public int compareTo(FactData factData) {
		long primaryKey = factData.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof FactData)) {
			return false;
		}

		FactData factData = (FactData)obj;

		long primaryKey = factData.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<FactData> toCacheModel() {
		FactDataCacheModel factDataCacheModel = new FactDataCacheModel();

		factDataCacheModel.factId = getFactId();

		factDataCacheModel.reportId = getReportId();

		factDataCacheModel.libraryId = getLibraryId();

		factDataCacheModel.period = getPeriod();

		String period = factDataCacheModel.period;

		if ((period != null) && (period.length() == 0)) {
			factDataCacheModel.period = null;
		}

		factDataCacheModel.dimensionId = getDimensionId();

		factDataCacheModel.measure1 = getMeasure1();

		factDataCacheModel.measure2 = getMeasure2();

		factDataCacheModel.measure3 = getMeasure3();

		factDataCacheModel.measure4 = getMeasure4();

		factDataCacheModel.companyId = getCompanyId();

		factDataCacheModel.groupId = getGroupId();

		factDataCacheModel.userId = getUserId();

		factDataCacheModel.userName = getUserName();

		String userName = factDataCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			factDataCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			factDataCacheModel.createDate = createDate.getTime();
		}
		else {
			factDataCacheModel.createDate = Long.MIN_VALUE;
		}

		return factDataCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{factId=");
		sb.append(getFactId());
		sb.append(", reportId=");
		sb.append(getReportId());
		sb.append(", libraryId=");
		sb.append(getLibraryId());
		sb.append(", period=");
		sb.append(getPeriod());
		sb.append(", dimensionId=");
		sb.append(getDimensionId());
		sb.append(", measure1=");
		sb.append(getMeasure1());
		sb.append(", measure2=");
		sb.append(getMeasure2());
		sb.append(", measure3=");
		sb.append(getMeasure3());
		sb.append(", measure4=");
		sb.append(getMeasure4());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("com.idetronic.eis.model.FactData");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>factId</column-name><column-value><![CDATA[");
		sb.append(getFactId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>reportId</column-name><column-value><![CDATA[");
		sb.append(getReportId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>libraryId</column-name><column-value><![CDATA[");
		sb.append(getLibraryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>period</column-name><column-value><![CDATA[");
		sb.append(getPeriod());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dimensionId</column-name><column-value><![CDATA[");
		sb.append(getDimensionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>measure1</column-name><column-value><![CDATA[");
		sb.append(getMeasure1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>measure2</column-name><column-value><![CDATA[");
		sb.append(getMeasure2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>measure3</column-name><column-value><![CDATA[");
		sb.append(getMeasure3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>measure4</column-name><column-value><![CDATA[");
		sb.append(getMeasure4());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = FactData.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			FactData.class
		};
	private long _factId;
	private long _reportId;
	private long _libraryId;
	private String _period;
	private long _dimensionId;
	private double _measure1;
	private double _measure2;
	private double _measure3;
	private double _measure4;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private FactData _escapedModel;
}