/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model.impl;

import com.idetronic.eis.model.FactDigitalCollection;
import com.idetronic.eis.service.FactDigitalCollectionLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the FactDigitalCollection service. Represents a row in the &quot;eis_FactDigitalCollection&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FactDigitalCollectionImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see FactDigitalCollectionImpl
 * @see com.idetronic.eis.model.FactDigitalCollection
 * @generated
 */
public abstract class FactDigitalCollectionBaseImpl
	extends FactDigitalCollectionModelImpl implements FactDigitalCollection {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fact digital collection model instance should use the {@link FactDigitalCollection} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			FactDigitalCollectionLocalServiceUtil.addFactDigitalCollection(this);
		}
		else {
			FactDigitalCollectionLocalServiceUtil.updateFactDigitalCollection(this);
		}
	}
}