/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model.impl;

import com.idetronic.eis.model.FactAcquisition;
import com.idetronic.eis.model.FactAcquisitionModel;
import com.idetronic.eis.model.FactAcquisitionSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the FactAcquisition service. Represents a row in the &quot;eis_FactAcquisition&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.idetronic.eis.model.FactAcquisitionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FactAcquisitionImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see FactAcquisitionImpl
 * @see com.idetronic.eis.model.FactAcquisition
 * @see com.idetronic.eis.model.FactAcquisitionModel
 * @generated
 */
@JSON(strict = true)
public class FactAcquisitionModelImpl extends BaseModelImpl<FactAcquisition>
	implements FactAcquisitionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fact acquisition model instance should use the {@link com.idetronic.eis.model.FactAcquisition} interface instead.
	 */
	public static final String TABLE_NAME = "eis_FactAcquisition";
	public static final Object[][] TABLE_COLUMNS = {
			{ "factAcquisitionId", Types.BIGINT },
			{ "libraryId", Types.BIGINT },
			{ "facultyId", Types.BIGINT },
			{ "period", Types.VARCHAR },
			{ "itemId", Types.BIGINT },
			{ "approvedTitleTotal", Types.BIGINT },
			{ "approvedVolumeTotal", Types.BIGINT },
			{ "approvedAmountTotal", Types.DOUBLE },
			{ "orderTitleTotal", Types.BIGINT },
			{ "orderVolumeTotal", Types.BIGINT },
			{ "orderAmountTotal", Types.DOUBLE },
			{ "volumeTotal", Types.BIGINT },
			{ "titleTotal", Types.BIGINT },
			{ "amountTotal", Types.DOUBLE },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table eis_FactAcquisition (factAcquisitionId LONG not null primary key,libraryId LONG,facultyId LONG,period VARCHAR(75) null,itemId LONG,approvedTitleTotal LONG,approvedVolumeTotal LONG,approvedAmountTotal DOUBLE,orderTitleTotal LONG,orderVolumeTotal LONG,orderAmountTotal DOUBLE,volumeTotal LONG,titleTotal LONG,amountTotal DOUBLE,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table eis_FactAcquisition";
	public static final String ORDER_BY_JPQL = " ORDER BY factAcquisition.factAcquisitionId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY eis_FactAcquisition.factAcquisitionId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.idetronic.eis.model.FactAcquisition"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.idetronic.eis.model.FactAcquisition"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.idetronic.eis.model.FactAcquisition"),
			true);
	public static long FACULTYID_COLUMN_BITMASK = 1L;
	public static long FACTACQUISITIONID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static FactAcquisition toModel(FactAcquisitionSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		FactAcquisition model = new FactAcquisitionImpl();

		model.setFactAcquisitionId(soapModel.getFactAcquisitionId());
		model.setLibraryId(soapModel.getLibraryId());
		model.setFacultyId(soapModel.getFacultyId());
		model.setPeriod(soapModel.getPeriod());
		model.setItemId(soapModel.getItemId());
		model.setApprovedTitleTotal(soapModel.getApprovedTitleTotal());
		model.setApprovedVolumeTotal(soapModel.getApprovedVolumeTotal());
		model.setApprovedAmountTotal(soapModel.getApprovedAmountTotal());
		model.setOrderTitleTotal(soapModel.getOrderTitleTotal());
		model.setOrderVolumeTotal(soapModel.getOrderVolumeTotal());
		model.setOrderAmountTotal(soapModel.getOrderAmountTotal());
		model.setVolumeTotal(soapModel.getVolumeTotal());
		model.setTitleTotal(soapModel.getTitleTotal());
		model.setAmountTotal(soapModel.getAmountTotal());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<FactAcquisition> toModels(
		FactAcquisitionSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<FactAcquisition> models = new ArrayList<FactAcquisition>(soapModels.length);

		for (FactAcquisitionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.idetronic.eis.model.FactAcquisition"));

	public FactAcquisitionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _factAcquisitionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFactAcquisitionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _factAcquisitionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FactAcquisition.class;
	}

	@Override
	public String getModelClassName() {
		return FactAcquisition.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("factAcquisitionId", getFactAcquisitionId());
		attributes.put("libraryId", getLibraryId());
		attributes.put("facultyId", getFacultyId());
		attributes.put("period", getPeriod());
		attributes.put("itemId", getItemId());
		attributes.put("approvedTitleTotal", getApprovedTitleTotal());
		attributes.put("approvedVolumeTotal", getApprovedVolumeTotal());
		attributes.put("approvedAmountTotal", getApprovedAmountTotal());
		attributes.put("orderTitleTotal", getOrderTitleTotal());
		attributes.put("orderVolumeTotal", getOrderVolumeTotal());
		attributes.put("orderAmountTotal", getOrderAmountTotal());
		attributes.put("volumeTotal", getVolumeTotal());
		attributes.put("titleTotal", getTitleTotal());
		attributes.put("amountTotal", getAmountTotal());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long factAcquisitionId = (Long)attributes.get("factAcquisitionId");

		if (factAcquisitionId != null) {
			setFactAcquisitionId(factAcquisitionId);
		}

		Long libraryId = (Long)attributes.get("libraryId");

		if (libraryId != null) {
			setLibraryId(libraryId);
		}

		Long facultyId = (Long)attributes.get("facultyId");

		if (facultyId != null) {
			setFacultyId(facultyId);
		}

		String period = (String)attributes.get("period");

		if (period != null) {
			setPeriod(period);
		}

		Long itemId = (Long)attributes.get("itemId");

		if (itemId != null) {
			setItemId(itemId);
		}

		Long approvedTitleTotal = (Long)attributes.get("approvedTitleTotal");

		if (approvedTitleTotal != null) {
			setApprovedTitleTotal(approvedTitleTotal);
		}

		Long approvedVolumeTotal = (Long)attributes.get("approvedVolumeTotal");

		if (approvedVolumeTotal != null) {
			setApprovedVolumeTotal(approvedVolumeTotal);
		}

		Double approvedAmountTotal = (Double)attributes.get(
				"approvedAmountTotal");

		if (approvedAmountTotal != null) {
			setApprovedAmountTotal(approvedAmountTotal);
		}

		Long orderTitleTotal = (Long)attributes.get("orderTitleTotal");

		if (orderTitleTotal != null) {
			setOrderTitleTotal(orderTitleTotal);
		}

		Long orderVolumeTotal = (Long)attributes.get("orderVolumeTotal");

		if (orderVolumeTotal != null) {
			setOrderVolumeTotal(orderVolumeTotal);
		}

		Double orderAmountTotal = (Double)attributes.get("orderAmountTotal");

		if (orderAmountTotal != null) {
			setOrderAmountTotal(orderAmountTotal);
		}

		Long volumeTotal = (Long)attributes.get("volumeTotal");

		if (volumeTotal != null) {
			setVolumeTotal(volumeTotal);
		}

		Long titleTotal = (Long)attributes.get("titleTotal");

		if (titleTotal != null) {
			setTitleTotal(titleTotal);
		}

		Double amountTotal = (Double)attributes.get("amountTotal");

		if (amountTotal != null) {
			setAmountTotal(amountTotal);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}
	}

	@JSON
	@Override
	public long getFactAcquisitionId() {
		return _factAcquisitionId;
	}

	@Override
	public void setFactAcquisitionId(long factAcquisitionId) {
		_factAcquisitionId = factAcquisitionId;
	}

	@JSON
	@Override
	public long getLibraryId() {
		return _libraryId;
	}

	@Override
	public void setLibraryId(long libraryId) {
		_libraryId = libraryId;
	}

	@JSON
	@Override
	public long getFacultyId() {
		return _facultyId;
	}

	@Override
	public void setFacultyId(long facultyId) {
		_columnBitmask |= FACULTYID_COLUMN_BITMASK;

		if (!_setOriginalFacultyId) {
			_setOriginalFacultyId = true;

			_originalFacultyId = _facultyId;
		}

		_facultyId = facultyId;
	}

	public long getOriginalFacultyId() {
		return _originalFacultyId;
	}

	@JSON
	@Override
	public String getPeriod() {
		if (_period == null) {
			return StringPool.BLANK;
		}
		else {
			return _period;
		}
	}

	@Override
	public void setPeriod(String period) {
		_period = period;
	}

	@JSON
	@Override
	public long getItemId() {
		return _itemId;
	}

	@Override
	public void setItemId(long itemId) {
		_itemId = itemId;
	}

	@JSON
	@Override
	public long getApprovedTitleTotal() {
		return _approvedTitleTotal;
	}

	@Override
	public void setApprovedTitleTotal(long approvedTitleTotal) {
		_approvedTitleTotal = approvedTitleTotal;
	}

	@JSON
	@Override
	public long getApprovedVolumeTotal() {
		return _approvedVolumeTotal;
	}

	@Override
	public void setApprovedVolumeTotal(long approvedVolumeTotal) {
		_approvedVolumeTotal = approvedVolumeTotal;
	}

	@JSON
	@Override
	public double getApprovedAmountTotal() {
		return _approvedAmountTotal;
	}

	@Override
	public void setApprovedAmountTotal(double approvedAmountTotal) {
		_approvedAmountTotal = approvedAmountTotal;
	}

	@JSON
	@Override
	public long getOrderTitleTotal() {
		return _orderTitleTotal;
	}

	@Override
	public void setOrderTitleTotal(long orderTitleTotal) {
		_orderTitleTotal = orderTitleTotal;
	}

	@JSON
	@Override
	public long getOrderVolumeTotal() {
		return _orderVolumeTotal;
	}

	@Override
	public void setOrderVolumeTotal(long orderVolumeTotal) {
		_orderVolumeTotal = orderVolumeTotal;
	}

	@JSON
	@Override
	public double getOrderAmountTotal() {
		return _orderAmountTotal;
	}

	@Override
	public void setOrderAmountTotal(double orderAmountTotal) {
		_orderAmountTotal = orderAmountTotal;
	}

	@JSON
	@Override
	public long getVolumeTotal() {
		return _volumeTotal;
	}

	@Override
	public void setVolumeTotal(long volumeTotal) {
		_volumeTotal = volumeTotal;
	}

	@JSON
	@Override
	public long getTitleTotal() {
		return _titleTotal;
	}

	@Override
	public void setTitleTotal(long titleTotal) {
		_titleTotal = titleTotal;
	}

	@JSON
	@Override
	public double getAmountTotal() {
		return _amountTotal;
	}

	@Override
	public void setAmountTotal(double amountTotal) {
		_amountTotal = amountTotal;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			FactAcquisition.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FactAcquisition toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (FactAcquisition)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FactAcquisitionImpl factAcquisitionImpl = new FactAcquisitionImpl();

		factAcquisitionImpl.setFactAcquisitionId(getFactAcquisitionId());
		factAcquisitionImpl.setLibraryId(getLibraryId());
		factAcquisitionImpl.setFacultyId(getFacultyId());
		factAcquisitionImpl.setPeriod(getPeriod());
		factAcquisitionImpl.setItemId(getItemId());
		factAcquisitionImpl.setApprovedTitleTotal(getApprovedTitleTotal());
		factAcquisitionImpl.setApprovedVolumeTotal(getApprovedVolumeTotal());
		factAcquisitionImpl.setApprovedAmountTotal(getApprovedAmountTotal());
		factAcquisitionImpl.setOrderTitleTotal(getOrderTitleTotal());
		factAcquisitionImpl.setOrderVolumeTotal(getOrderVolumeTotal());
		factAcquisitionImpl.setOrderAmountTotal(getOrderAmountTotal());
		factAcquisitionImpl.setVolumeTotal(getVolumeTotal());
		factAcquisitionImpl.setTitleTotal(getTitleTotal());
		factAcquisitionImpl.setAmountTotal(getAmountTotal());
		factAcquisitionImpl.setCompanyId(getCompanyId());
		factAcquisitionImpl.setGroupId(getGroupId());
		factAcquisitionImpl.setUserId(getUserId());
		factAcquisitionImpl.setUserName(getUserName());
		factAcquisitionImpl.setCreateDate(getCreateDate());

		factAcquisitionImpl.resetOriginalValues();

		return factAcquisitionImpl;
	}

	@Override
	public int compareTo(FactAcquisition factAcquisition) {
		long primaryKey = factAcquisition.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof FactAcquisition)) {
			return false;
		}

		FactAcquisition factAcquisition = (FactAcquisition)obj;

		long primaryKey = factAcquisition.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		FactAcquisitionModelImpl factAcquisitionModelImpl = this;

		factAcquisitionModelImpl._originalFacultyId = factAcquisitionModelImpl._facultyId;

		factAcquisitionModelImpl._setOriginalFacultyId = false;

		factAcquisitionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<FactAcquisition> toCacheModel() {
		FactAcquisitionCacheModel factAcquisitionCacheModel = new FactAcquisitionCacheModel();

		factAcquisitionCacheModel.factAcquisitionId = getFactAcquisitionId();

		factAcquisitionCacheModel.libraryId = getLibraryId();

		factAcquisitionCacheModel.facultyId = getFacultyId();

		factAcquisitionCacheModel.period = getPeriod();

		String period = factAcquisitionCacheModel.period;

		if ((period != null) && (period.length() == 0)) {
			factAcquisitionCacheModel.period = null;
		}

		factAcquisitionCacheModel.itemId = getItemId();

		factAcquisitionCacheModel.approvedTitleTotal = getApprovedTitleTotal();

		factAcquisitionCacheModel.approvedVolumeTotal = getApprovedVolumeTotal();

		factAcquisitionCacheModel.approvedAmountTotal = getApprovedAmountTotal();

		factAcquisitionCacheModel.orderTitleTotal = getOrderTitleTotal();

		factAcquisitionCacheModel.orderVolumeTotal = getOrderVolumeTotal();

		factAcquisitionCacheModel.orderAmountTotal = getOrderAmountTotal();

		factAcquisitionCacheModel.volumeTotal = getVolumeTotal();

		factAcquisitionCacheModel.titleTotal = getTitleTotal();

		factAcquisitionCacheModel.amountTotal = getAmountTotal();

		factAcquisitionCacheModel.companyId = getCompanyId();

		factAcquisitionCacheModel.groupId = getGroupId();

		factAcquisitionCacheModel.userId = getUserId();

		factAcquisitionCacheModel.userName = getUserName();

		String userName = factAcquisitionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			factAcquisitionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			factAcquisitionCacheModel.createDate = createDate.getTime();
		}
		else {
			factAcquisitionCacheModel.createDate = Long.MIN_VALUE;
		}

		return factAcquisitionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(39);

		sb.append("{factAcquisitionId=");
		sb.append(getFactAcquisitionId());
		sb.append(", libraryId=");
		sb.append(getLibraryId());
		sb.append(", facultyId=");
		sb.append(getFacultyId());
		sb.append(", period=");
		sb.append(getPeriod());
		sb.append(", itemId=");
		sb.append(getItemId());
		sb.append(", approvedTitleTotal=");
		sb.append(getApprovedTitleTotal());
		sb.append(", approvedVolumeTotal=");
		sb.append(getApprovedVolumeTotal());
		sb.append(", approvedAmountTotal=");
		sb.append(getApprovedAmountTotal());
		sb.append(", orderTitleTotal=");
		sb.append(getOrderTitleTotal());
		sb.append(", orderVolumeTotal=");
		sb.append(getOrderVolumeTotal());
		sb.append(", orderAmountTotal=");
		sb.append(getOrderAmountTotal());
		sb.append(", volumeTotal=");
		sb.append(getVolumeTotal());
		sb.append(", titleTotal=");
		sb.append(getTitleTotal());
		sb.append(", amountTotal=");
		sb.append(getAmountTotal());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(61);

		sb.append("<model><model-name>");
		sb.append("com.idetronic.eis.model.FactAcquisition");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>factAcquisitionId</column-name><column-value><![CDATA[");
		sb.append(getFactAcquisitionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>libraryId</column-name><column-value><![CDATA[");
		sb.append(getLibraryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>facultyId</column-name><column-value><![CDATA[");
		sb.append(getFacultyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>period</column-name><column-value><![CDATA[");
		sb.append(getPeriod());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>itemId</column-name><column-value><![CDATA[");
		sb.append(getItemId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>approvedTitleTotal</column-name><column-value><![CDATA[");
		sb.append(getApprovedTitleTotal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>approvedVolumeTotal</column-name><column-value><![CDATA[");
		sb.append(getApprovedVolumeTotal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>approvedAmountTotal</column-name><column-value><![CDATA[");
		sb.append(getApprovedAmountTotal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>orderTitleTotal</column-name><column-value><![CDATA[");
		sb.append(getOrderTitleTotal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>orderVolumeTotal</column-name><column-value><![CDATA[");
		sb.append(getOrderVolumeTotal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>orderAmountTotal</column-name><column-value><![CDATA[");
		sb.append(getOrderAmountTotal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>volumeTotal</column-name><column-value><![CDATA[");
		sb.append(getVolumeTotal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>titleTotal</column-name><column-value><![CDATA[");
		sb.append(getTitleTotal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>amountTotal</column-name><column-value><![CDATA[");
		sb.append(getAmountTotal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = FactAcquisition.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			FactAcquisition.class
		};
	private long _factAcquisitionId;
	private long _libraryId;
	private long _facultyId;
	private long _originalFacultyId;
	private boolean _setOriginalFacultyId;
	private String _period;
	private long _itemId;
	private long _approvedTitleTotal;
	private long _approvedVolumeTotal;
	private double _approvedAmountTotal;
	private long _orderTitleTotal;
	private long _orderVolumeTotal;
	private double _orderAmountTotal;
	private long _volumeTotal;
	private long _titleTotal;
	private double _amountTotal;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private long _columnBitmask;
	private FactAcquisition _escapedModel;
}