/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model.impl;

import com.idetronic.eis.model.FactVisitor;
import com.idetronic.eis.model.FactVisitorModel;
import com.idetronic.eis.model.FactVisitorSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the FactVisitor service. Represents a row in the &quot;eis_FactVisitor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.idetronic.eis.model.FactVisitorModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FactVisitorImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see FactVisitorImpl
 * @see com.idetronic.eis.model.FactVisitor
 * @see com.idetronic.eis.model.FactVisitorModel
 * @generated
 */
@JSON(strict = true)
public class FactVisitorModelImpl extends BaseModelImpl<FactVisitor>
	implements FactVisitorModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fact visitor model instance should use the {@link com.idetronic.eis.model.FactVisitor} interface instead.
	 */
	public static final String TABLE_NAME = "eis_FactVisitor";
	public static final Object[][] TABLE_COLUMNS = {
			{ "factVisitorId", Types.BIGINT },
			{ "libraryId", Types.BIGINT },
			{ "period", Types.VARCHAR },
			{ "visitorCategoryId", Types.BIGINT },
			{ "stateId", Types.BIGINT },
			{ "libraryTypeId", Types.BIGINT },
			{ "value", Types.INTEGER },
			{ "createdByUserId", Types.BIGINT },
			{ "createdByUserName", Types.VARCHAR },
			{ "createdDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table eis_FactVisitor (factVisitorId LONG not null primary key,libraryId LONG,period VARCHAR(10) null,visitorCategoryId LONG,stateId LONG,libraryTypeId LONG,value INTEGER,createdByUserId LONG,createdByUserName VARCHAR(75) null,createdDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table eis_FactVisitor";
	public static final String ORDER_BY_JPQL = " ORDER BY factVisitor.factVisitorId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY eis_FactVisitor.factVisitorId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.idetronic.eis.model.FactVisitor"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.idetronic.eis.model.FactVisitor"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.idetronic.eis.model.FactVisitor"),
			true);
	public static long LIBRARYID_COLUMN_BITMASK = 1L;
	public static long PERIOD_COLUMN_BITMASK = 2L;
	public static long VISITORCATEGORYID_COLUMN_BITMASK = 4L;
	public static long FACTVISITORID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static FactVisitor toModel(FactVisitorSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		FactVisitor model = new FactVisitorImpl();

		model.setFactVisitorId(soapModel.getFactVisitorId());
		model.setLibraryId(soapModel.getLibraryId());
		model.setPeriod(soapModel.getPeriod());
		model.setVisitorCategoryId(soapModel.getVisitorCategoryId());
		model.setStateId(soapModel.getStateId());
		model.setLibraryTypeId(soapModel.getLibraryTypeId());
		model.setValue(soapModel.getValue());
		model.setCreatedByUserId(soapModel.getCreatedByUserId());
		model.setCreatedByUserName(soapModel.getCreatedByUserName());
		model.setCreatedDate(soapModel.getCreatedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<FactVisitor> toModels(FactVisitorSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<FactVisitor> models = new ArrayList<FactVisitor>(soapModels.length);

		for (FactVisitorSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.idetronic.eis.model.FactVisitor"));

	public FactVisitorModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _factVisitorId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFactVisitorId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _factVisitorId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FactVisitor.class;
	}

	@Override
	public String getModelClassName() {
		return FactVisitor.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("factVisitorId", getFactVisitorId());
		attributes.put("libraryId", getLibraryId());
		attributes.put("period", getPeriod());
		attributes.put("visitorCategoryId", getVisitorCategoryId());
		attributes.put("stateId", getStateId());
		attributes.put("libraryTypeId", getLibraryTypeId());
		attributes.put("value", getValue());
		attributes.put("createdByUserId", getCreatedByUserId());
		attributes.put("createdByUserName", getCreatedByUserName());
		attributes.put("createdDate", getCreatedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long factVisitorId = (Long)attributes.get("factVisitorId");

		if (factVisitorId != null) {
			setFactVisitorId(factVisitorId);
		}

		Long libraryId = (Long)attributes.get("libraryId");

		if (libraryId != null) {
			setLibraryId(libraryId);
		}

		String period = (String)attributes.get("period");

		if (period != null) {
			setPeriod(period);
		}

		Long visitorCategoryId = (Long)attributes.get("visitorCategoryId");

		if (visitorCategoryId != null) {
			setVisitorCategoryId(visitorCategoryId);
		}

		Long stateId = (Long)attributes.get("stateId");

		if (stateId != null) {
			setStateId(stateId);
		}

		Long libraryTypeId = (Long)attributes.get("libraryTypeId");

		if (libraryTypeId != null) {
			setLibraryTypeId(libraryTypeId);
		}

		Integer value = (Integer)attributes.get("value");

		if (value != null) {
			setValue(value);
		}

		Long createdByUserId = (Long)attributes.get("createdByUserId");

		if (createdByUserId != null) {
			setCreatedByUserId(createdByUserId);
		}

		String createdByUserName = (String)attributes.get("createdByUserName");

		if (createdByUserName != null) {
			setCreatedByUserName(createdByUserName);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}
	}

	@JSON
	@Override
	public long getFactVisitorId() {
		return _factVisitorId;
	}

	@Override
	public void setFactVisitorId(long factVisitorId) {
		_factVisitorId = factVisitorId;
	}

	@JSON
	@Override
	public long getLibraryId() {
		return _libraryId;
	}

	@Override
	public void setLibraryId(long libraryId) {
		_columnBitmask |= LIBRARYID_COLUMN_BITMASK;

		if (!_setOriginalLibraryId) {
			_setOriginalLibraryId = true;

			_originalLibraryId = _libraryId;
		}

		_libraryId = libraryId;
	}

	public long getOriginalLibraryId() {
		return _originalLibraryId;
	}

	@JSON
	@Override
	public String getPeriod() {
		if (_period == null) {
			return StringPool.BLANK;
		}
		else {
			return _period;
		}
	}

	@Override
	public void setPeriod(String period) {
		_columnBitmask |= PERIOD_COLUMN_BITMASK;

		if (_originalPeriod == null) {
			_originalPeriod = _period;
		}

		_period = period;
	}

	public String getOriginalPeriod() {
		return GetterUtil.getString(_originalPeriod);
	}

	@JSON
	@Override
	public long getVisitorCategoryId() {
		return _visitorCategoryId;
	}

	@Override
	public void setVisitorCategoryId(long visitorCategoryId) {
		_columnBitmask |= VISITORCATEGORYID_COLUMN_BITMASK;

		if (!_setOriginalVisitorCategoryId) {
			_setOriginalVisitorCategoryId = true;

			_originalVisitorCategoryId = _visitorCategoryId;
		}

		_visitorCategoryId = visitorCategoryId;
	}

	public long getOriginalVisitorCategoryId() {
		return _originalVisitorCategoryId;
	}

	@JSON
	@Override
	public long getStateId() {
		return _stateId;
	}

	@Override
	public void setStateId(long stateId) {
		_stateId = stateId;
	}

	@JSON
	@Override
	public long getLibraryTypeId() {
		return _libraryTypeId;
	}

	@Override
	public void setLibraryTypeId(long libraryTypeId) {
		_libraryTypeId = libraryTypeId;
	}

	@JSON
	@Override
	public int getValue() {
		return _value;
	}

	@Override
	public void setValue(int value) {
		_value = value;
	}

	@JSON
	@Override
	public long getCreatedByUserId() {
		return _createdByUserId;
	}

	@Override
	public void setCreatedByUserId(long createdByUserId) {
		_createdByUserId = createdByUserId;
	}

	@Override
	public String getCreatedByUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getCreatedByUserId(), "uuid",
			_createdByUserUuid);
	}

	@Override
	public void setCreatedByUserUuid(String createdByUserUuid) {
		_createdByUserUuid = createdByUserUuid;
	}

	@JSON
	@Override
	public String getCreatedByUserName() {
		if (_createdByUserName == null) {
			return StringPool.BLANK;
		}
		else {
			return _createdByUserName;
		}
	}

	@Override
	public void setCreatedByUserName(String createdByUserName) {
		_createdByUserName = createdByUserName;
	}

	@JSON
	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			FactVisitor.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FactVisitor toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (FactVisitor)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FactVisitorImpl factVisitorImpl = new FactVisitorImpl();

		factVisitorImpl.setFactVisitorId(getFactVisitorId());
		factVisitorImpl.setLibraryId(getLibraryId());
		factVisitorImpl.setPeriod(getPeriod());
		factVisitorImpl.setVisitorCategoryId(getVisitorCategoryId());
		factVisitorImpl.setStateId(getStateId());
		factVisitorImpl.setLibraryTypeId(getLibraryTypeId());
		factVisitorImpl.setValue(getValue());
		factVisitorImpl.setCreatedByUserId(getCreatedByUserId());
		factVisitorImpl.setCreatedByUserName(getCreatedByUserName());
		factVisitorImpl.setCreatedDate(getCreatedDate());

		factVisitorImpl.resetOriginalValues();

		return factVisitorImpl;
	}

	@Override
	public int compareTo(FactVisitor factVisitor) {
		long primaryKey = factVisitor.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof FactVisitor)) {
			return false;
		}

		FactVisitor factVisitor = (FactVisitor)obj;

		long primaryKey = factVisitor.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		FactVisitorModelImpl factVisitorModelImpl = this;

		factVisitorModelImpl._originalLibraryId = factVisitorModelImpl._libraryId;

		factVisitorModelImpl._setOriginalLibraryId = false;

		factVisitorModelImpl._originalPeriod = factVisitorModelImpl._period;

		factVisitorModelImpl._originalVisitorCategoryId = factVisitorModelImpl._visitorCategoryId;

		factVisitorModelImpl._setOriginalVisitorCategoryId = false;

		factVisitorModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<FactVisitor> toCacheModel() {
		FactVisitorCacheModel factVisitorCacheModel = new FactVisitorCacheModel();

		factVisitorCacheModel.factVisitorId = getFactVisitorId();

		factVisitorCacheModel.libraryId = getLibraryId();

		factVisitorCacheModel.period = getPeriod();

		String period = factVisitorCacheModel.period;

		if ((period != null) && (period.length() == 0)) {
			factVisitorCacheModel.period = null;
		}

		factVisitorCacheModel.visitorCategoryId = getVisitorCategoryId();

		factVisitorCacheModel.stateId = getStateId();

		factVisitorCacheModel.libraryTypeId = getLibraryTypeId();

		factVisitorCacheModel.value = getValue();

		factVisitorCacheModel.createdByUserId = getCreatedByUserId();

		factVisitorCacheModel.createdByUserName = getCreatedByUserName();

		String createdByUserName = factVisitorCacheModel.createdByUserName;

		if ((createdByUserName != null) && (createdByUserName.length() == 0)) {
			factVisitorCacheModel.createdByUserName = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			factVisitorCacheModel.createdDate = createdDate.getTime();
		}
		else {
			factVisitorCacheModel.createdDate = Long.MIN_VALUE;
		}

		return factVisitorCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{factVisitorId=");
		sb.append(getFactVisitorId());
		sb.append(", libraryId=");
		sb.append(getLibraryId());
		sb.append(", period=");
		sb.append(getPeriod());
		sb.append(", visitorCategoryId=");
		sb.append(getVisitorCategoryId());
		sb.append(", stateId=");
		sb.append(getStateId());
		sb.append(", libraryTypeId=");
		sb.append(getLibraryTypeId());
		sb.append(", value=");
		sb.append(getValue());
		sb.append(", createdByUserId=");
		sb.append(getCreatedByUserId());
		sb.append(", createdByUserName=");
		sb.append(getCreatedByUserName());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.idetronic.eis.model.FactVisitor");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>factVisitorId</column-name><column-value><![CDATA[");
		sb.append(getFactVisitorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>libraryId</column-name><column-value><![CDATA[");
		sb.append(getLibraryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>period</column-name><column-value><![CDATA[");
		sb.append(getPeriod());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>visitorCategoryId</column-name><column-value><![CDATA[");
		sb.append(getVisitorCategoryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>stateId</column-name><column-value><![CDATA[");
		sb.append(getStateId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>libraryTypeId</column-name><column-value><![CDATA[");
		sb.append(getLibraryTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>value</column-name><column-value><![CDATA[");
		sb.append(getValue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdByUserId</column-name><column-value><![CDATA[");
		sb.append(getCreatedByUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdByUserName</column-name><column-value><![CDATA[");
		sb.append(getCreatedByUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = FactVisitor.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			FactVisitor.class
		};
	private long _factVisitorId;
	private long _libraryId;
	private long _originalLibraryId;
	private boolean _setOriginalLibraryId;
	private String _period;
	private String _originalPeriod;
	private long _visitorCategoryId;
	private long _originalVisitorCategoryId;
	private boolean _setOriginalVisitorCategoryId;
	private long _stateId;
	private long _libraryTypeId;
	private int _value;
	private long _createdByUserId;
	private String _createdByUserUuid;
	private String _createdByUserName;
	private Date _createdDate;
	private long _columnBitmask;
	private FactVisitor _escapedModel;
}