/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model.impl;

import com.idetronic.eis.model.ItemType;
import com.idetronic.eis.model.ItemTypeModel;
import com.idetronic.eis.model.ItemTypeSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ItemType service. Represents a row in the &quot;eis_ItemType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.idetronic.eis.model.ItemTypeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ItemTypeImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see ItemTypeImpl
 * @see com.idetronic.eis.model.ItemType
 * @see com.idetronic.eis.model.ItemTypeModel
 * @generated
 */
@JSON(strict = true)
public class ItemTypeModelImpl extends BaseModelImpl<ItemType>
	implements ItemTypeModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a item type model instance should use the {@link com.idetronic.eis.model.ItemType} interface instead.
	 */
	public static final String TABLE_NAME = "eis_ItemType";
	public static final Object[][] TABLE_COLUMNS = {
			{ "itemTypeId", Types.BIGINT },
			{ "itemTypeName", Types.VARCHAR },
			{ "printedType", Types.INTEGER },
			{ "IRType", Types.BOOLEAN },
			{ "active_", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table eis_ItemType (itemTypeId LONG not null primary key,itemTypeName VARCHAR(75) null,printedType INTEGER,IRType BOOLEAN,active_ BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table eis_ItemType";
	public static final String ORDER_BY_JPQL = " ORDER BY itemType.itemTypeId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY eis_ItemType.itemTypeId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.idetronic.eis.model.ItemType"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.idetronic.eis.model.ItemType"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.idetronic.eis.model.ItemType"),
			true);
	public static long IRTYPE_COLUMN_BITMASK = 1L;
	public static long PRINTEDTYPE_COLUMN_BITMASK = 2L;
	public static long ITEMTYPEID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ItemType toModel(ItemTypeSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ItemType model = new ItemTypeImpl();

		model.setItemTypeId(soapModel.getItemTypeId());
		model.setItemTypeName(soapModel.getItemTypeName());
		model.setPrintedType(soapModel.getPrintedType());
		model.setIRType(soapModel.getIRType());
		model.setActive(soapModel.getActive());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ItemType> toModels(ItemTypeSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ItemType> models = new ArrayList<ItemType>(soapModels.length);

		for (ItemTypeSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.idetronic.eis.model.ItemType"));

	public ItemTypeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _itemTypeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setItemTypeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _itemTypeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ItemType.class;
	}

	@Override
	public String getModelClassName() {
		return ItemType.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("itemTypeId", getItemTypeId());
		attributes.put("itemTypeName", getItemTypeName());
		attributes.put("printedType", getPrintedType());
		attributes.put("IRType", getIRType());
		attributes.put("active", getActive());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long itemTypeId = (Long)attributes.get("itemTypeId");

		if (itemTypeId != null) {
			setItemTypeId(itemTypeId);
		}

		String itemTypeName = (String)attributes.get("itemTypeName");

		if (itemTypeName != null) {
			setItemTypeName(itemTypeName);
		}

		Integer printedType = (Integer)attributes.get("printedType");

		if (printedType != null) {
			setPrintedType(printedType);
		}

		Boolean IRType = (Boolean)attributes.get("IRType");

		if (IRType != null) {
			setIRType(IRType);
		}

		Boolean active = (Boolean)attributes.get("active");

		if (active != null) {
			setActive(active);
		}
	}

	@JSON
	@Override
	public long getItemTypeId() {
		return _itemTypeId;
	}

	@Override
	public void setItemTypeId(long itemTypeId) {
		_itemTypeId = itemTypeId;
	}

	@JSON
	@Override
	public String getItemTypeName() {
		if (_itemTypeName == null) {
			return StringPool.BLANK;
		}
		else {
			return _itemTypeName;
		}
	}

	@Override
	public void setItemTypeName(String itemTypeName) {
		_itemTypeName = itemTypeName;
	}

	@JSON
	@Override
	public int getPrintedType() {
		return _printedType;
	}

	@Override
	public void setPrintedType(int printedType) {
		_columnBitmask |= PRINTEDTYPE_COLUMN_BITMASK;

		if (!_setOriginalPrintedType) {
			_setOriginalPrintedType = true;

			_originalPrintedType = _printedType;
		}

		_printedType = printedType;
	}

	public int getOriginalPrintedType() {
		return _originalPrintedType;
	}

	@JSON
	@Override
	public boolean getIRType() {
		return _IRType;
	}

	@Override
	public boolean isIRType() {
		return _IRType;
	}

	@Override
	public void setIRType(boolean IRType) {
		_columnBitmask |= IRTYPE_COLUMN_BITMASK;

		if (!_setOriginalIRType) {
			_setOriginalIRType = true;

			_originalIRType = _IRType;
		}

		_IRType = IRType;
	}

	public boolean getOriginalIRType() {
		return _originalIRType;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_active = active;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ItemType.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ItemType toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ItemType)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ItemTypeImpl itemTypeImpl = new ItemTypeImpl();

		itemTypeImpl.setItemTypeId(getItemTypeId());
		itemTypeImpl.setItemTypeName(getItemTypeName());
		itemTypeImpl.setPrintedType(getPrintedType());
		itemTypeImpl.setIRType(getIRType());
		itemTypeImpl.setActive(getActive());

		itemTypeImpl.resetOriginalValues();

		return itemTypeImpl;
	}

	@Override
	public int compareTo(ItemType itemType) {
		long primaryKey = itemType.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ItemType)) {
			return false;
		}

		ItemType itemType = (ItemType)obj;

		long primaryKey = itemType.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ItemTypeModelImpl itemTypeModelImpl = this;

		itemTypeModelImpl._originalPrintedType = itemTypeModelImpl._printedType;

		itemTypeModelImpl._setOriginalPrintedType = false;

		itemTypeModelImpl._originalIRType = itemTypeModelImpl._IRType;

		itemTypeModelImpl._setOriginalIRType = false;

		itemTypeModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ItemType> toCacheModel() {
		ItemTypeCacheModel itemTypeCacheModel = new ItemTypeCacheModel();

		itemTypeCacheModel.itemTypeId = getItemTypeId();

		itemTypeCacheModel.itemTypeName = getItemTypeName();

		String itemTypeName = itemTypeCacheModel.itemTypeName;

		if ((itemTypeName != null) && (itemTypeName.length() == 0)) {
			itemTypeCacheModel.itemTypeName = null;
		}

		itemTypeCacheModel.printedType = getPrintedType();

		itemTypeCacheModel.IRType = getIRType();

		itemTypeCacheModel.active = getActive();

		return itemTypeCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{itemTypeId=");
		sb.append(getItemTypeId());
		sb.append(", itemTypeName=");
		sb.append(getItemTypeName());
		sb.append(", printedType=");
		sb.append(getPrintedType());
		sb.append(", IRType=");
		sb.append(getIRType());
		sb.append(", active=");
		sb.append(getActive());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.idetronic.eis.model.ItemType");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>itemTypeId</column-name><column-value><![CDATA[");
		sb.append(getItemTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>itemTypeName</column-name><column-value><![CDATA[");
		sb.append(getItemTypeName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>printedType</column-name><column-value><![CDATA[");
		sb.append(getPrintedType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>IRType</column-name><column-value><![CDATA[");
		sb.append(getIRType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>active</column-name><column-value><![CDATA[");
		sb.append(getActive());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ItemType.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ItemType.class
		};
	private long _itemTypeId;
	private String _itemTypeName;
	private int _printedType;
	private int _originalPrintedType;
	private boolean _setOriginalPrintedType;
	private boolean _IRType;
	private boolean _originalIRType;
	private boolean _setOriginalIRType;
	private boolean _active;
	private long _columnBitmask;
	private ItemType _escapedModel;
}