/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model.impl;

import com.idetronic.eis.model.ItemTypeCategory;
import com.idetronic.eis.model.ItemTypeCategoryModel;
import com.idetronic.eis.model.ItemTypeCategorySoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ItemTypeCategory service. Represents a row in the &quot;eis_ItemTypeCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.idetronic.eis.model.ItemTypeCategoryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ItemTypeCategoryImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see ItemTypeCategoryImpl
 * @see com.idetronic.eis.model.ItemTypeCategory
 * @see com.idetronic.eis.model.ItemTypeCategoryModel
 * @generated
 */
@JSON(strict = true)
public class ItemTypeCategoryModelImpl extends BaseModelImpl<ItemTypeCategory>
	implements ItemTypeCategoryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a item type category model instance should use the {@link com.idetronic.eis.model.ItemTypeCategory} interface instead.
	 */
	public static final String TABLE_NAME = "eis_ItemTypeCategory";
	public static final Object[][] TABLE_COLUMNS = {
			{ "itemTypeCategoryId", Types.BIGINT },
			{ "itemTypeCategoryName", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table eis_ItemTypeCategory (itemTypeCategoryId LONG not null primary key,itemTypeCategoryName VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table eis_ItemTypeCategory";
	public static final String ORDER_BY_JPQL = " ORDER BY itemTypeCategory.itemTypeCategoryId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY eis_ItemTypeCategory.itemTypeCategoryId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.idetronic.eis.model.ItemTypeCategory"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.idetronic.eis.model.ItemTypeCategory"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ItemTypeCategory toModel(ItemTypeCategorySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ItemTypeCategory model = new ItemTypeCategoryImpl();

		model.setItemTypeCategoryId(soapModel.getItemTypeCategoryId());
		model.setItemTypeCategoryName(soapModel.getItemTypeCategoryName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ItemTypeCategory> toModels(
		ItemTypeCategorySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ItemTypeCategory> models = new ArrayList<ItemTypeCategory>(soapModels.length);

		for (ItemTypeCategorySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.idetronic.eis.model.ItemTypeCategory"));

	public ItemTypeCategoryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _itemTypeCategoryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setItemTypeCategoryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _itemTypeCategoryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ItemTypeCategory.class;
	}

	@Override
	public String getModelClassName() {
		return ItemTypeCategory.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("itemTypeCategoryId", getItemTypeCategoryId());
		attributes.put("itemTypeCategoryName", getItemTypeCategoryName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long itemTypeCategoryId = (Long)attributes.get("itemTypeCategoryId");

		if (itemTypeCategoryId != null) {
			setItemTypeCategoryId(itemTypeCategoryId);
		}

		String itemTypeCategoryName = (String)attributes.get(
				"itemTypeCategoryName");

		if (itemTypeCategoryName != null) {
			setItemTypeCategoryName(itemTypeCategoryName);
		}
	}

	@JSON
	@Override
	public long getItemTypeCategoryId() {
		return _itemTypeCategoryId;
	}

	@Override
	public void setItemTypeCategoryId(long itemTypeCategoryId) {
		_itemTypeCategoryId = itemTypeCategoryId;
	}

	@JSON
	@Override
	public String getItemTypeCategoryName() {
		if (_itemTypeCategoryName == null) {
			return StringPool.BLANK;
		}
		else {
			return _itemTypeCategoryName;
		}
	}

	@Override
	public void setItemTypeCategoryName(String itemTypeCategoryName) {
		_itemTypeCategoryName = itemTypeCategoryName;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ItemTypeCategory.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ItemTypeCategory toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ItemTypeCategory)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ItemTypeCategoryImpl itemTypeCategoryImpl = new ItemTypeCategoryImpl();

		itemTypeCategoryImpl.setItemTypeCategoryId(getItemTypeCategoryId());
		itemTypeCategoryImpl.setItemTypeCategoryName(getItemTypeCategoryName());

		itemTypeCategoryImpl.resetOriginalValues();

		return itemTypeCategoryImpl;
	}

	@Override
	public int compareTo(ItemTypeCategory itemTypeCategory) {
		long primaryKey = itemTypeCategory.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ItemTypeCategory)) {
			return false;
		}

		ItemTypeCategory itemTypeCategory = (ItemTypeCategory)obj;

		long primaryKey = itemTypeCategory.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<ItemTypeCategory> toCacheModel() {
		ItemTypeCategoryCacheModel itemTypeCategoryCacheModel = new ItemTypeCategoryCacheModel();

		itemTypeCategoryCacheModel.itemTypeCategoryId = getItemTypeCategoryId();

		itemTypeCategoryCacheModel.itemTypeCategoryName = getItemTypeCategoryName();

		String itemTypeCategoryName = itemTypeCategoryCacheModel.itemTypeCategoryName;

		if ((itemTypeCategoryName != null) &&
				(itemTypeCategoryName.length() == 0)) {
			itemTypeCategoryCacheModel.itemTypeCategoryName = null;
		}

		return itemTypeCategoryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{itemTypeCategoryId=");
		sb.append(getItemTypeCategoryId());
		sb.append(", itemTypeCategoryName=");
		sb.append(getItemTypeCategoryName());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.idetronic.eis.model.ItemTypeCategory");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>itemTypeCategoryId</column-name><column-value><![CDATA[");
		sb.append(getItemTypeCategoryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>itemTypeCategoryName</column-name><column-value><![CDATA[");
		sb.append(getItemTypeCategoryName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ItemTypeCategory.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ItemTypeCategory.class
		};
	private long _itemTypeCategoryId;
	private String _itemTypeCategoryName;
	private ItemTypeCategory _escapedModel;
}