/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model.impl;

import com.idetronic.eis.model.LibrarySeatingDepartment;
import com.idetronic.eis.model.LibrarySeatingDepartmentModel;
import com.idetronic.eis.model.LibrarySeatingDepartmentSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the LibrarySeatingDepartment service. Represents a row in the &quot;eis_LibrarySeatingDepartment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.idetronic.eis.model.LibrarySeatingDepartmentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LibrarySeatingDepartmentImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see LibrarySeatingDepartmentImpl
 * @see com.idetronic.eis.model.LibrarySeatingDepartment
 * @see com.idetronic.eis.model.LibrarySeatingDepartmentModel
 * @generated
 */
@JSON(strict = true)
public class LibrarySeatingDepartmentModelImpl extends BaseModelImpl<LibrarySeatingDepartment>
	implements LibrarySeatingDepartmentModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a library seating department model instance should use the {@link com.idetronic.eis.model.LibrarySeatingDepartment} interface instead.
	 */
	public static final String TABLE_NAME = "eis_LibrarySeatingDepartment";
	public static final Object[][] TABLE_COLUMNS = {
			{ "libraryDepartmentId", Types.BIGINT },
			{ "libraryId", Types.BIGINT },
			{ "departmentId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table eis_LibrarySeatingDepartment (libraryDepartmentId LONG not null primary key,libraryId LONG,departmentId LONG,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table eis_LibrarySeatingDepartment";
	public static final String ORDER_BY_JPQL = " ORDER BY librarySeatingDepartment.libraryDepartmentId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY eis_LibrarySeatingDepartment.libraryDepartmentId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.idetronic.eis.model.LibrarySeatingDepartment"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.idetronic.eis.model.LibrarySeatingDepartment"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.idetronic.eis.model.LibrarySeatingDepartment"),
			true);
	public static long DEPARTMENTID_COLUMN_BITMASK = 1L;
	public static long LIBRARYID_COLUMN_BITMASK = 2L;
	public static long LIBRARYDEPARTMENTID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LibrarySeatingDepartment toModel(
		LibrarySeatingDepartmentSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LibrarySeatingDepartment model = new LibrarySeatingDepartmentImpl();

		model.setLibraryDepartmentId(soapModel.getLibraryDepartmentId());
		model.setLibraryId(soapModel.getLibraryId());
		model.setDepartmentId(soapModel.getDepartmentId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LibrarySeatingDepartment> toModels(
		LibrarySeatingDepartmentSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LibrarySeatingDepartment> models = new ArrayList<LibrarySeatingDepartment>(soapModels.length);

		for (LibrarySeatingDepartmentSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.idetronic.eis.model.LibrarySeatingDepartment"));

	public LibrarySeatingDepartmentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _libraryDepartmentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLibraryDepartmentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _libraryDepartmentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LibrarySeatingDepartment.class;
	}

	@Override
	public String getModelClassName() {
		return LibrarySeatingDepartment.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("libraryDepartmentId", getLibraryDepartmentId());
		attributes.put("libraryId", getLibraryId());
		attributes.put("departmentId", getDepartmentId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long libraryDepartmentId = (Long)attributes.get("libraryDepartmentId");

		if (libraryDepartmentId != null) {
			setLibraryDepartmentId(libraryDepartmentId);
		}

		Long libraryId = (Long)attributes.get("libraryId");

		if (libraryId != null) {
			setLibraryId(libraryId);
		}

		Long departmentId = (Long)attributes.get("departmentId");

		if (departmentId != null) {
			setDepartmentId(departmentId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@JSON
	@Override
	public long getLibraryDepartmentId() {
		return _libraryDepartmentId;
	}

	@Override
	public void setLibraryDepartmentId(long libraryDepartmentId) {
		_libraryDepartmentId = libraryDepartmentId;
	}

	@JSON
	@Override
	public long getLibraryId() {
		return _libraryId;
	}

	@Override
	public void setLibraryId(long libraryId) {
		_columnBitmask |= LIBRARYID_COLUMN_BITMASK;

		if (!_setOriginalLibraryId) {
			_setOriginalLibraryId = true;

			_originalLibraryId = _libraryId;
		}

		_libraryId = libraryId;
	}

	public long getOriginalLibraryId() {
		return _originalLibraryId;
	}

	@JSON
	@Override
	public long getDepartmentId() {
		return _departmentId;
	}

	@Override
	public void setDepartmentId(long departmentId) {
		_columnBitmask |= DEPARTMENTID_COLUMN_BITMASK;

		if (!_setOriginalDepartmentId) {
			_setOriginalDepartmentId = true;

			_originalDepartmentId = _departmentId;
		}

		_departmentId = departmentId;
	}

	public long getOriginalDepartmentId() {
		return _originalDepartmentId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			LibrarySeatingDepartment.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LibrarySeatingDepartment toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LibrarySeatingDepartment)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LibrarySeatingDepartmentImpl librarySeatingDepartmentImpl = new LibrarySeatingDepartmentImpl();

		librarySeatingDepartmentImpl.setLibraryDepartmentId(getLibraryDepartmentId());
		librarySeatingDepartmentImpl.setLibraryId(getLibraryId());
		librarySeatingDepartmentImpl.setDepartmentId(getDepartmentId());
		librarySeatingDepartmentImpl.setCompanyId(getCompanyId());
		librarySeatingDepartmentImpl.setGroupId(getGroupId());
		librarySeatingDepartmentImpl.setUserId(getUserId());
		librarySeatingDepartmentImpl.setUserName(getUserName());
		librarySeatingDepartmentImpl.setCreateDate(getCreateDate());
		librarySeatingDepartmentImpl.setModifiedDate(getModifiedDate());

		librarySeatingDepartmentImpl.resetOriginalValues();

		return librarySeatingDepartmentImpl;
	}

	@Override
	public int compareTo(LibrarySeatingDepartment librarySeatingDepartment) {
		long primaryKey = librarySeatingDepartment.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LibrarySeatingDepartment)) {
			return false;
		}

		LibrarySeatingDepartment librarySeatingDepartment = (LibrarySeatingDepartment)obj;

		long primaryKey = librarySeatingDepartment.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		LibrarySeatingDepartmentModelImpl librarySeatingDepartmentModelImpl = this;

		librarySeatingDepartmentModelImpl._originalLibraryId = librarySeatingDepartmentModelImpl._libraryId;

		librarySeatingDepartmentModelImpl._setOriginalLibraryId = false;

		librarySeatingDepartmentModelImpl._originalDepartmentId = librarySeatingDepartmentModelImpl._departmentId;

		librarySeatingDepartmentModelImpl._setOriginalDepartmentId = false;

		librarySeatingDepartmentModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LibrarySeatingDepartment> toCacheModel() {
		LibrarySeatingDepartmentCacheModel librarySeatingDepartmentCacheModel = new LibrarySeatingDepartmentCacheModel();

		librarySeatingDepartmentCacheModel.libraryDepartmentId = getLibraryDepartmentId();

		librarySeatingDepartmentCacheModel.libraryId = getLibraryId();

		librarySeatingDepartmentCacheModel.departmentId = getDepartmentId();

		librarySeatingDepartmentCacheModel.companyId = getCompanyId();

		librarySeatingDepartmentCacheModel.groupId = getGroupId();

		librarySeatingDepartmentCacheModel.userId = getUserId();

		librarySeatingDepartmentCacheModel.userName = getUserName();

		String userName = librarySeatingDepartmentCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			librarySeatingDepartmentCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			librarySeatingDepartmentCacheModel.createDate = createDate.getTime();
		}
		else {
			librarySeatingDepartmentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			librarySeatingDepartmentCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			librarySeatingDepartmentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return librarySeatingDepartmentCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{libraryDepartmentId=");
		sb.append(getLibraryDepartmentId());
		sb.append(", libraryId=");
		sb.append(getLibraryId());
		sb.append(", departmentId=");
		sb.append(getDepartmentId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.idetronic.eis.model.LibrarySeatingDepartment");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>libraryDepartmentId</column-name><column-value><![CDATA[");
		sb.append(getLibraryDepartmentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>libraryId</column-name><column-value><![CDATA[");
		sb.append(getLibraryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>departmentId</column-name><column-value><![CDATA[");
		sb.append(getDepartmentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = LibrarySeatingDepartment.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			LibrarySeatingDepartment.class
		};
	private long _libraryDepartmentId;
	private long _libraryId;
	private long _originalLibraryId;
	private boolean _setOriginalLibraryId;
	private long _departmentId;
	private long _originalDepartmentId;
	private boolean _setOriginalDepartmentId;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _columnBitmask;
	private LibrarySeatingDepartment _escapedModel;
}