/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model.impl;

import com.idetronic.eis.model.ProjectResourceType;
import com.idetronic.eis.model.ProjectResourceTypeModel;
import com.idetronic.eis.model.ProjectResourceTypeSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ProjectResourceType service. Represents a row in the &quot;eis_ProjectResourceType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.idetronic.eis.model.ProjectResourceTypeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProjectResourceTypeImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see ProjectResourceTypeImpl
 * @see com.idetronic.eis.model.ProjectResourceType
 * @see com.idetronic.eis.model.ProjectResourceTypeModel
 * @generated
 */
@JSON(strict = true)
public class ProjectResourceTypeModelImpl extends BaseModelImpl<ProjectResourceType>
	implements ProjectResourceTypeModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a project resource type model instance should use the {@link com.idetronic.eis.model.ProjectResourceType} interface instead.
	 */
	public static final String TABLE_NAME = "eis_ProjectResourceType";
	public static final Object[][] TABLE_COLUMNS = {
			{ "projectResourceTypeId", Types.BIGINT },
			{ "resourceTypeName", Types.VARCHAR },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table eis_ProjectResourceType (projectResourceTypeId LONG not null primary key,resourceTypeName VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table eis_ProjectResourceType";
	public static final String ORDER_BY_JPQL = " ORDER BY projectResourceType.projectResourceTypeId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY eis_ProjectResourceType.projectResourceTypeId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.idetronic.eis.model.ProjectResourceType"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.idetronic.eis.model.ProjectResourceType"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ProjectResourceType toModel(ProjectResourceTypeSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ProjectResourceType model = new ProjectResourceTypeImpl();

		model.setProjectResourceTypeId(soapModel.getProjectResourceTypeId());
		model.setResourceTypeName(soapModel.getResourceTypeName());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ProjectResourceType> toModels(
		ProjectResourceTypeSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ProjectResourceType> models = new ArrayList<ProjectResourceType>(soapModels.length);

		for (ProjectResourceTypeSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.idetronic.eis.model.ProjectResourceType"));

	public ProjectResourceTypeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _projectResourceTypeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProjectResourceTypeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _projectResourceTypeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProjectResourceType.class;
	}

	@Override
	public String getModelClassName() {
		return ProjectResourceType.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("projectResourceTypeId", getProjectResourceTypeId());
		attributes.put("resourceTypeName", getResourceTypeName());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long projectResourceTypeId = (Long)attributes.get(
				"projectResourceTypeId");

		if (projectResourceTypeId != null) {
			setProjectResourceTypeId(projectResourceTypeId);
		}

		String resourceTypeName = (String)attributes.get("resourceTypeName");

		if (resourceTypeName != null) {
			setResourceTypeName(resourceTypeName);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@JSON
	@Override
	public long getProjectResourceTypeId() {
		return _projectResourceTypeId;
	}

	@Override
	public void setProjectResourceTypeId(long projectResourceTypeId) {
		_projectResourceTypeId = projectResourceTypeId;
	}

	@JSON
	@Override
	public String getResourceTypeName() {
		if (_resourceTypeName == null) {
			return StringPool.BLANK;
		}
		else {
			return _resourceTypeName;
		}
	}

	@Override
	public void setResourceTypeName(String resourceTypeName) {
		_resourceTypeName = resourceTypeName;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ProjectResourceType.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProjectResourceType toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ProjectResourceType)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProjectResourceTypeImpl projectResourceTypeImpl = new ProjectResourceTypeImpl();

		projectResourceTypeImpl.setProjectResourceTypeId(getProjectResourceTypeId());
		projectResourceTypeImpl.setResourceTypeName(getResourceTypeName());
		projectResourceTypeImpl.setGroupId(getGroupId());
		projectResourceTypeImpl.setCompanyId(getCompanyId());
		projectResourceTypeImpl.setUserId(getUserId());
		projectResourceTypeImpl.setUserName(getUserName());
		projectResourceTypeImpl.setCreateDate(getCreateDate());
		projectResourceTypeImpl.setModifiedDate(getModifiedDate());

		projectResourceTypeImpl.resetOriginalValues();

		return projectResourceTypeImpl;
	}

	@Override
	public int compareTo(ProjectResourceType projectResourceType) {
		long primaryKey = projectResourceType.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ProjectResourceType)) {
			return false;
		}

		ProjectResourceType projectResourceType = (ProjectResourceType)obj;

		long primaryKey = projectResourceType.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<ProjectResourceType> toCacheModel() {
		ProjectResourceTypeCacheModel projectResourceTypeCacheModel = new ProjectResourceTypeCacheModel();

		projectResourceTypeCacheModel.projectResourceTypeId = getProjectResourceTypeId();

		projectResourceTypeCacheModel.resourceTypeName = getResourceTypeName();

		String resourceTypeName = projectResourceTypeCacheModel.resourceTypeName;

		if ((resourceTypeName != null) && (resourceTypeName.length() == 0)) {
			projectResourceTypeCacheModel.resourceTypeName = null;
		}

		projectResourceTypeCacheModel.groupId = getGroupId();

		projectResourceTypeCacheModel.companyId = getCompanyId();

		projectResourceTypeCacheModel.userId = getUserId();

		projectResourceTypeCacheModel.userName = getUserName();

		String userName = projectResourceTypeCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			projectResourceTypeCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			projectResourceTypeCacheModel.createDate = createDate.getTime();
		}
		else {
			projectResourceTypeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			projectResourceTypeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			projectResourceTypeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return projectResourceTypeCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{projectResourceTypeId=");
		sb.append(getProjectResourceTypeId());
		sb.append(", resourceTypeName=");
		sb.append(getResourceTypeName());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.idetronic.eis.model.ProjectResourceType");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>projectResourceTypeId</column-name><column-value><![CDATA[");
		sb.append(getProjectResourceTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>resourceTypeName</column-name><column-value><![CDATA[");
		sb.append(getResourceTypeName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ProjectResourceType.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ProjectResourceType.class
		};
	private long _projectResourceTypeId;
	private String _resourceTypeName;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private ProjectResourceType _escapedModel;
}