/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eis.model.impl;

import com.idetronic.eis.model.SeatingCategory;
import com.idetronic.eis.model.SeatingCategoryModel;
import com.idetronic.eis.model.SeatingCategorySoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the SeatingCategory service. Represents a row in the &quot;eis_SeatingCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.idetronic.eis.model.SeatingCategoryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SeatingCategoryImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see SeatingCategoryImpl
 * @see com.idetronic.eis.model.SeatingCategory
 * @see com.idetronic.eis.model.SeatingCategoryModel
 * @generated
 */
@JSON(strict = true)
public class SeatingCategoryModelImpl extends BaseModelImpl<SeatingCategory>
	implements SeatingCategoryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a seating category model instance should use the {@link com.idetronic.eis.model.SeatingCategory} interface instead.
	 */
	public static final String TABLE_NAME = "eis_SeatingCategory";
	public static final Object[][] TABLE_COLUMNS = {
			{ "seatingCategoryId", Types.BIGINT },
			{ "seatingCategoryName", Types.VARCHAR },
			{ "seatingDepartmentId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table eis_SeatingCategory (seatingCategoryId LONG not null primary key,seatingCategoryName VARCHAR(75) null,seatingDepartmentId LONG,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table eis_SeatingCategory";
	public static final String ORDER_BY_JPQL = " ORDER BY seatingCategory.seatingCategoryId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY eis_SeatingCategory.seatingCategoryId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.idetronic.eis.model.SeatingCategory"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.idetronic.eis.model.SeatingCategory"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.idetronic.eis.model.SeatingCategory"),
			true);
	public static long SEATINGDEPARTMENTID_COLUMN_BITMASK = 1L;
	public static long SEATINGCATEGORYID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static SeatingCategory toModel(SeatingCategorySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SeatingCategory model = new SeatingCategoryImpl();

		model.setSeatingCategoryId(soapModel.getSeatingCategoryId());
		model.setSeatingCategoryName(soapModel.getSeatingCategoryName());
		model.setSeatingDepartmentId(soapModel.getSeatingDepartmentId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<SeatingCategory> toModels(
		SeatingCategorySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SeatingCategory> models = new ArrayList<SeatingCategory>(soapModels.length);

		for (SeatingCategorySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.idetronic.eis.model.SeatingCategory"));

	public SeatingCategoryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _seatingCategoryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSeatingCategoryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _seatingCategoryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SeatingCategory.class;
	}

	@Override
	public String getModelClassName() {
		return SeatingCategory.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("seatingCategoryId", getSeatingCategoryId());
		attributes.put("seatingCategoryName", getSeatingCategoryName());
		attributes.put("seatingDepartmentId", getSeatingDepartmentId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long seatingCategoryId = (Long)attributes.get("seatingCategoryId");

		if (seatingCategoryId != null) {
			setSeatingCategoryId(seatingCategoryId);
		}

		String seatingCategoryName = (String)attributes.get(
				"seatingCategoryName");

		if (seatingCategoryName != null) {
			setSeatingCategoryName(seatingCategoryName);
		}

		Long seatingDepartmentId = (Long)attributes.get("seatingDepartmentId");

		if (seatingDepartmentId != null) {
			setSeatingDepartmentId(seatingDepartmentId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@JSON
	@Override
	public long getSeatingCategoryId() {
		return _seatingCategoryId;
	}

	@Override
	public void setSeatingCategoryId(long seatingCategoryId) {
		_seatingCategoryId = seatingCategoryId;
	}

	@JSON
	@Override
	public String getSeatingCategoryName() {
		if (_seatingCategoryName == null) {
			return StringPool.BLANK;
		}
		else {
			return _seatingCategoryName;
		}
	}

	@Override
	public void setSeatingCategoryName(String seatingCategoryName) {
		_seatingCategoryName = seatingCategoryName;
	}

	@JSON
	@Override
	public long getSeatingDepartmentId() {
		return _seatingDepartmentId;
	}

	@Override
	public void setSeatingDepartmentId(long seatingDepartmentId) {
		_columnBitmask |= SEATINGDEPARTMENTID_COLUMN_BITMASK;

		if (!_setOriginalSeatingDepartmentId) {
			_setOriginalSeatingDepartmentId = true;

			_originalSeatingDepartmentId = _seatingDepartmentId;
		}

		_seatingDepartmentId = seatingDepartmentId;
	}

	public long getOriginalSeatingDepartmentId() {
		return _originalSeatingDepartmentId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			SeatingCategory.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SeatingCategory toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SeatingCategory)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SeatingCategoryImpl seatingCategoryImpl = new SeatingCategoryImpl();

		seatingCategoryImpl.setSeatingCategoryId(getSeatingCategoryId());
		seatingCategoryImpl.setSeatingCategoryName(getSeatingCategoryName());
		seatingCategoryImpl.setSeatingDepartmentId(getSeatingDepartmentId());
		seatingCategoryImpl.setCompanyId(getCompanyId());
		seatingCategoryImpl.setGroupId(getGroupId());
		seatingCategoryImpl.setUserId(getUserId());
		seatingCategoryImpl.setUserName(getUserName());
		seatingCategoryImpl.setCreateDate(getCreateDate());
		seatingCategoryImpl.setModifiedDate(getModifiedDate());

		seatingCategoryImpl.resetOriginalValues();

		return seatingCategoryImpl;
	}

	@Override
	public int compareTo(SeatingCategory seatingCategory) {
		long primaryKey = seatingCategory.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SeatingCategory)) {
			return false;
		}

		SeatingCategory seatingCategory = (SeatingCategory)obj;

		long primaryKey = seatingCategory.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		SeatingCategoryModelImpl seatingCategoryModelImpl = this;

		seatingCategoryModelImpl._originalSeatingDepartmentId = seatingCategoryModelImpl._seatingDepartmentId;

		seatingCategoryModelImpl._setOriginalSeatingDepartmentId = false;

		seatingCategoryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SeatingCategory> toCacheModel() {
		SeatingCategoryCacheModel seatingCategoryCacheModel = new SeatingCategoryCacheModel();

		seatingCategoryCacheModel.seatingCategoryId = getSeatingCategoryId();

		seatingCategoryCacheModel.seatingCategoryName = getSeatingCategoryName();

		String seatingCategoryName = seatingCategoryCacheModel.seatingCategoryName;

		if ((seatingCategoryName != null) &&
				(seatingCategoryName.length() == 0)) {
			seatingCategoryCacheModel.seatingCategoryName = null;
		}

		seatingCategoryCacheModel.seatingDepartmentId = getSeatingDepartmentId();

		seatingCategoryCacheModel.companyId = getCompanyId();

		seatingCategoryCacheModel.groupId = getGroupId();

		seatingCategoryCacheModel.userId = getUserId();

		seatingCategoryCacheModel.userName = getUserName();

		String userName = seatingCategoryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			seatingCategoryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			seatingCategoryCacheModel.createDate = createDate.getTime();
		}
		else {
			seatingCategoryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			seatingCategoryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			seatingCategoryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return seatingCategoryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{seatingCategoryId=");
		sb.append(getSeatingCategoryId());
		sb.append(", seatingCategoryName=");
		sb.append(getSeatingCategoryName());
		sb.append(", seatingDepartmentId=");
		sb.append(getSeatingDepartmentId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.idetronic.eis.model.SeatingCategory");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>seatingCategoryId</column-name><column-value><![CDATA[");
		sb.append(getSeatingCategoryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>seatingCategoryName</column-name><column-value><![CDATA[");
		sb.append(getSeatingCategoryName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>seatingDepartmentId</column-name><column-value><![CDATA[");
		sb.append(getSeatingDepartmentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = SeatingCategory.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			SeatingCategory.class
		};
	private long _seatingCategoryId;
	private String _seatingCategoryName;
	private long _seatingDepartmentId;
	private long _originalSeatingDepartmentId;
	private boolean _setOriginalSeatingDepartmentId;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _columnBitmask;
	private SeatingCategory _escapedModel;
}